import { build } from 'esbuild';
import { cp, mkdir } from 'node:fs/promises';

/**
 * Builds the browser bundle. The canonical core is unchanged: this only strips
 * types and bundles ESM for Safari. Node adapters are never pulled in — the
 * browser entry point imports only the IndexedDB and Web Audio adapters.
 */
await mkdir('web/dist', { recursive: true });
const result = await build({
  entryPoints: ['src/web/lab.ts'],
  outfile: 'web/lab.js',
  bundle: true,
  format: 'esm',
  target: ['safari17'],
  platform: 'browser',
  minify: false,
  sourcemap: false,
  banner: { js: '// Generated by build.mjs from src/web/lab.ts — do not edit directly.' },
  footer: { js: 'export { openWebLab as openLab };' },
  metafile: true,
});
const bytes = Object.values(result.metafile.outputs)[0]?.bytes ?? 0;
console.log(`web/lab.js built: ${(bytes / 1024).toFixed(1)} KB`);
