import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { SqliteRecordStore } from '../../src/adapters/node-sqlite/record-store.ts';
import { FsContentStore } from '../../src/adapters/content-fs/content-store.ts';
import { DataRegistry } from '../../src/registries/data-registry.ts';
import { registerAlchemyVocabulary } from '../../src/domain/alchemy/vocabulary.ts';
import { AlchemyService } from '../../src/domain/alchemy/service.ts';
import { AlchemyQueries } from '../../src/query/queries.ts';
import { migrate, CURRENT_SCHEMA } from '../../src/migrations/index.ts';
import { synthesize, encodeWav, decodeWav } from '../../src/audio/wav.ts';
import { contentHash } from '../../src/core/ids.ts';
import {
  runMesaExploration, validateMesaState, serializeMesaState, DEFAULT_MESA_STATE,
  MEDIUM_STRATEGIES, UNEXPECTED_STRATEGIES, deriveStrategySeed, MESA_CONFIGURATION_ID, MESA_VERSION,
} from '../../src/domain/alchemy/mesa.ts';
import { FRAGMENT_EXPLORATION_V1, FRAGMENT_EXPLORATION_V1_1, FRAGMENT_EXPLORATION_V1_2 }
  from '../../src/domain/alchemy/research-configuration.ts';

const src = (seed = 9, frames = 4000) => encodeWav(synthesize(seed, 8000, 1, frames));

// ---- Mesa state ---------------------------------------------------------------

test('1+2+3. MesaState validates and clamps all eight controls', () => {
  const state = validateMesaState({
    fragmentar: { escala: -20, desorden: 150 }, acelerar: { tiempo: 50.6, movimiento: -1 },
    microscopio: { zoom: 200, persistencia: 0 }, excitar: { energia: 100, estabilidad: -50 },
  });
  assert.equal(state.fragmentar.escala, 0, 'below 0 clamps to 0');
  assert.equal(state.fragmentar.desorden, 100, 'above 100 clamps to 100');
  assert.equal(state.acelerar.movimiento, 0);
  assert.equal(state.microscopio.zoom, 100);
  assert.equal(state.excitar.estabilidad, 0);
  assert.ok(Number.isInteger(state.acelerar.tiempo), 'values round to integers');
});

test('4. same MesaState serializes deterministically', () => {
  const a = serializeMesaState(DEFAULT_MESA_STATE);
  const b = serializeMesaState(DEFAULT_MESA_STATE);
  assert.equal(a, b);
});

test('5. Mesa is not persisted as a canonical Entity', async () => {
  const { readFile } = await import('node:fs/promises');
  const source = await readFile('src/domain/alchemy/mesa.ts', 'utf8');
  assert.ok(!/COLLECTIONS\.entities|\.commit\(/.test(source),
    'mesa.ts never writes to persistence; MesaState is validated and translated entirely in memory');
});

// ---- distribution ---------------------------------------------------------------

test('6+7+8+10. exactly 8 Previews, 4 Medium, 4 Unexpected, deterministic order', () => {
  const obs = runMesaExploration(src(), DEFAULT_MESA_STATE, 1000);
  assert.equal(obs.length, 8);
  assert.equal(obs.filter((o) => o.territory === 'medium').length, 4);
  assert.equal(obs.filter((o) => o.territory === 'unexpected').length, 4);
  assert.deepEqual(obs.slice(0, 4).map((o) => o.territory), ['medium', 'medium', 'medium', 'medium']);
  assert.deepEqual(obs.slice(4).map((o) => o.territory), ['unexpected', 'unexpected', 'unexpected', 'unexpected']);
  const obs2 = runMesaExploration(src(), DEFAULT_MESA_STATE, 1000);
  assert.deepEqual(obs.map((o) => o.strategyId), obs2.map((o) => o.strategyId), 'ordering is deterministic');
});

test('9. no Preview is the unmodified source', () => {
  const bytes = src();
  const sourceHash = contentHash(bytes);
  const obs = runMesaExploration(bytes, DEFAULT_MESA_STATE, 1000);
  for (const o of obs) assert.notEqual(contentHash(o.bytes), sourceHash);
});

// ---- strategies -------------------------------------------------------------------

test('11+12+13. strategy identifiers are distinct and selection is deterministic', () => {
  assert.equal(new Set(MEDIUM_STRATEGIES.map((s) => s.id)).size, 4);
  assert.equal(new Set(UNEXPECTED_STRATEGIES.map((s) => s.id)).size, 4);
  const obs1 = runMesaExploration(src(), DEFAULT_MESA_STATE, 42);
  const obs2 = runMesaExploration(src(), DEFAULT_MESA_STATE, 42);
  assert.deepEqual(obs1.map((o) => o.strategyId), obs2.map((o) => o.strategyId));
});

test('14. outputs are not generated by seeds alone under one identical strategy', () => {
  // Different strategies at the same territory produce different weights, so
  // hashes differ even with related seeds -- confirmed by the earlier
  // uniqueness check, and explicitly here for the four Medium strategies.
  const obs = runMesaExploration(src(), DEFAULT_MESA_STATE, 1000);
  const mediumHashes = new Set(obs.slice(0, 4).map((o) => contentHash(o.bytes)));
  assert.equal(mediumHashes.size, 4);
});

test('15+16. each Unexpected records a preservation anchor; more than one strategy used', () => {
  const obs = runMesaExploration(src(), DEFAULT_MESA_STATE, 1000);
  const unexpected = obs.filter((o) => o.territory === 'unexpected');
  for (const o of unexpected) assert.ok(o.anchor !== null, `${o.strategyId} must declare an anchor`);
  assert.ok(new Set(unexpected.map((o) => o.anchor)).size > 1, 'anchors differ across Unexpected strategies');
});

// ---- determinism ------------------------------------------------------------------

test('17+18. identical inputs are bit-identical; alone vs. inside the set match', () => {
  const bytes = src();
  const a = runMesaExploration(bytes, DEFAULT_MESA_STATE, 500);
  const b = runMesaExploration(bytes, DEFAULT_MESA_STATE, 500);
  for (let i = 0; i < 8; i++) {
    assert.deepEqual(Buffer.from(a[i].bytes), Buffer.from(b[i].bytes));
  }
});

test('19. seed derivation is reproducible and documented', () => {
  const a = deriveStrategySeed(1000, 'medium', 2);
  const b = deriveStrategySeed(1000, 'medium', 2);
  const c = deriveStrategySeed(1000, 'unexpected', 2);
  assert.equal(a, b);
  assert.notEqual(a, c, 'territory changes the derived seed even with the same strategy index');
});

test('20. different strategy indices produce distinct hashes for the reference fixture', () => {
  const obs = runMesaExploration(src(), DEFAULT_MESA_STATE, 1000);
  assert.equal(new Set(obs.map((o) => contentHash(o.bytes))).size, 8);
});

test('21. fragment-exploration-v1 reference hashes remain byte-identical (all three versions)', () => {
  const s = encodeWav(synthesize(9, 8000, 1, 5000));
  assert.equal(contentHash(FRAGMENT_EXPLORATION_V1.render(
    s, FRAGMENT_EXPLORATION_V1.variationSeed(1000, 0))).slice(0, 10), '19e8cbc4f1');
  assert.equal(contentHash(FRAGMENT_EXPLORATION_V1_1.render(
    s, FRAGMENT_EXPLORATION_V1_1.variationSeed(1000, 0))).slice(0, 10), 'ec99208e04');
  assert.equal(contentHash(FRAGMENT_EXPLORATION_V1_2.render(
    s, FRAGMENT_EXPLORATION_V1_2.variationSeed(1000, 0))).slice(0, 10), '344526b806');
});

// ---- audio safety -----------------------------------------------------------------

test('22+24+25. frames stay channel-aligned, no clipping, silence is safe', () => {
  const silent = encodeWav({ sampleRate: 8000, channels: 1, samples: new Int16Array(2000) });
  const obs = runMesaExploration(silent, DEFAULT_MESA_STATE, 1);
  assert.equal(obs.length, 8);
  for (const o of obs) {
    const audio = decodeWav(o.bytes);
    assert.equal(audio.samples.length % audio.channels, 0, 'sample count is frame-aligned');
    for (const s of audio.samples) assert.ok(Math.abs(s) < 32768);
    assert.ok(Number.isFinite(audio.samples[0] ?? 0));
  }
});

test('26+27. very short input remains safe', () => {
  const tiny = encodeWav({ sampleRate: 8000, channels: 1, samples: new Int16Array(64).fill(5000) });
  const obs = runMesaExploration(tiny, DEFAULT_MESA_STATE, 1);
  assert.equal(obs.length, 8);
  for (const o of obs) assert.ok(decodeWav(o.bytes).samples.length >= 0);
});

test('28. temporal transformation preserves valid WAV structure', () => {
  const obs = runMesaExploration(src(), DEFAULT_MESA_STATE, 1);
  for (const o of obs) {
    const audio = decodeWav(o.bytes); // throws on malformed structure
    assert.equal(audio.sampleRate, 8000);
    assert.equal(audio.channels, 1);
  }
});

// ---- lifecycle / provenance ---------------------------------------------------------

async function lab() {
  const dir = mkdtempSync(join(tmpdir(), 'spk-mesa-'));
  const records = new SqliteRecordStore(join(dir, 'store.sqlite'), CURRENT_SCHEMA);
  await migrate(records);
  const content = new FsContentStore(join(dir, 'content'));
  const registry = new DataRegistry();
  registerAlchemyVocabulary(registry);
  const service = new AlchemyService(records, content, registry);
  const queries = new AlchemyQueries(records, content);
  const artist = await service.registerAgent({ kind: 'human', name: 'artist', version: '1' });
  return { records, content, service, queries, artist };
}

test('29+36. Mesa Preview generation persists no Material; siblings remain nonpersistent', async () => {
  const { COLLECTIONS } = await import('../../src/core/primitives.ts');
  const materialCount = async () => (await l.records.scan(COLLECTIONS.entities, null, 500)).items
    .filter((e) => (e as { role?: string }).role === 'material').length;
  const l = await lab();
  const source = await l.service.importMaterial({ bytes: src(3), filename: 's.wav', agentId: l.artist.id });
  const intent = await l.service.createResearchIntent({ question: 'q', agentId: l.artist.id });
  const before = await materialCount();
  // Running the exploration legitimately creates one Experiment Entity (as
  // fragment-exploration-v1 already does) -- the claim under test is about
  // Materials specifically: eight Previews, zero new Materials.
  await l.service.runMesaExploration({
    materialId: source.id, researchIntentId: intent.id, mesaState: DEFAULT_MESA_STATE, baseSeed: 1, agentId: l.artist.id });
  const after = await materialCount();
  assert.equal(after, before, 'eight Previews, zero new Materials');
  await l.records.close();
});

test('30+31+32+33+34+35. Retain records complete Mesa provenance', async () => {
  const l = await lab();
  const source = await l.service.importMaterial({ bytes: src(3), filename: 's.wav', agentId: l.artist.id });
  const intent = await l.service.createResearchIntent({ question: 'q', agentId: l.artist.id });
  const set = await l.service.runMesaExploration({
    materialId: source.id, researchIntentId: intent.id, mesaState: DEFAULT_MESA_STATE, baseSeed: 7, agentId: l.artist.id });
  const chosen = set.variations.find((v) => v.territory === 'unexpected')!;
  const r = await l.service.retain(chosen.preview, l.artist.id);
  assert.equal(r.created, true, 'exactly one Material created');
  assert.equal(r.material.attributes.configurationId, MESA_CONFIGURATION_ID);
  assert.equal(r.material.attributes.configurationVersion, MESA_VERSION);
  const p = r.material.attributes.parameters as Record<string, unknown>;
  assert.deepEqual(p.mesaState, DEFAULT_MESA_STATE);
  assert.equal(p.territory, chosen.territory);
  assert.equal(p.strategyId, chosen.strategyId);
  assert.equal(p.anchor, chosen.anchor);
  await l.records.close();
});

test('37+38+39. retained Mesa output can be explored again; genealogy and lineage color root are correct', async () => {
  const l = await lab();
  const source = await l.service.importMaterial({ bytes: src(3), filename: 's.wav', agentId: l.artist.id });
  const intent = await l.service.createResearchIntent({ question: 'q', agentId: l.artist.id });
  const set1 = await l.service.runMesaExploration({
    materialId: source.id, researchIntentId: intent.id, mesaState: DEFAULT_MESA_STATE, baseSeed: 11, agentId: l.artist.id });
  const b = await l.service.retain(set1.variations[4].preview, l.artist.id); // first Unexpected
  await l.service.promote(b.material.id, l.artist.id);

  const set2 = await l.service.runMesaExploration({
    materialId: b.material.id, researchIntentId: intent.id, mesaState: DEFAULT_MESA_STATE, baseSeed: 22, agentId: l.artist.id });
  assert.equal(set2.variations.length, 8, 'a retained Mesa output is a valid Mesa input');
  const c = await l.service.retain(set2.variations[0].preview, l.artist.id);

  const ancestors = await l.queries.ancestors(c.material.id);
  assert.deepEqual(ancestors.nodes.map((n) => n.id), [b.material.id, source.id], 'genealogy A -> B -> C');

  const { resolveLineageRoot } = await import('../../src/domain/alchemy/lineage.ts');
  const resolved = await resolveLineageRoot(c.material.id, l.queries);
  assert.equal(resolved.rootId, source.id, 'lineage color root remains the original import');
  await l.records.close();
});

// ---- cross-source behavior -----------------------------------------------------------

test('40+41+42. unrelated sources do not collapse toward identical Unexpected outputs', () => {
  const a = src(3, 4000), b = src(77, 4000);
  const obsA = runMesaExploration(a, DEFAULT_MESA_STATE, 1000);
  const obsB = runMesaExploration(b, DEFAULT_MESA_STATE, 1000);
  let collapsed = 0;
  for (let i = 0; i < 8; i++) if (contentHash(obsA[i].bytes) === contentHash(obsB[i].bytes)) collapsed += 1;
  assert.equal(collapsed, 0, 'no strategy produces byte-identical output across unrelated sources');

  // Even at extreme MesaState, source-derived anchors keep provenance distinct.
  const extreme = {
    fragmentar: { escala: 100, desorden: 100 }, acelerar: { tiempo: 100, movimiento: 100 },
    microscopio: { zoom: 100, persistencia: 100 }, excitar: { energia: 100, estabilidad: 100 },
  };
  const obsAe = runMesaExploration(a, extreme, 1000);
  const obsBe = runMesaExploration(b, extreme, 1000);
  let collapsedExtreme = 0;
  for (let i = 0; i < 8; i++) if (contentHash(obsAe[i].bytes) === contentHash(obsBe[i].bytes)) collapsedExtreme += 1;
  assert.equal(collapsedExtreme, 0, 'no collapse even at maximum intensity on every control');
});

// ---- browser/runtime purity -----------------------------------------------------------

test('47. Mesa modules remain free of Node built-ins', async () => {
  const { readFile } = await import('node:fs/promises');
  for (const file of ['src/domain/alchemy/mesa.ts', 'src/audio/operations.ts']) {
    const source = await readFile(file, 'utf8');
    assert.ok(!/from ['"]node:/.test(source), `${file} must not import Node built-ins`);
  }
});

test('49. Family/DNA Pack workflows remain unaffected by Mesa', async () => {
  const l = await lab();
  const { FamilyService } = await import('../../src/domain/alchemy/family-service.ts');
  const registry = new DataRegistry();
  registerAlchemyVocabulary(registry);
  const families = new FamilyService(l.records, l.content, registry);
  const a = await l.service.importMaterial({ bytes: src(5), filename: 'a.wav', agentId: l.artist.id });
  const family = await families.createFamily({ name: 'F', materialIds: [a.id], agentId: l.artist.id });
  assert.equal(family.attributes.name, 'F');
  await l.records.close();
});
