import type { AudioBuffer } from '../../audio/wav.ts';
import { decodeWav, encodeWav } from '../../audio/wav.ts';
import {
  seededRandom, fragmentEvenly, shuffleWithSeed, sliceFragment,
  reverseFrames, applyGain, silence, concatSamples, applyBoundaryFade,
} from '../../audio/operations.ts';

/**
 * ResearchConfiguration — a versioned domain configuration contract.
 *
 * It is NOT a canonical structural primitive and NOT a persistent Entity in
 * this phase. It is executable, versioned configuration; what persists on
 * Retain is its id, version, operation sequence, parameters and seed, recorded
 * in the resulting Material's provenance.
 *
 * A change to generated bytes is a new version, never a silent edit to an
 * existing one — see FRAGMENT_EXPLORATION_V1 (unchanged) and
 * FRAGMENT_EXPLORATION_V1_1 (adds Preview-level gain correction) below.
 */

export const RESEARCH_CONFIGURATION_SCHEMA_VERSION = 1;

export interface OperationStep {
  operation: string;
  description: string;
}

export interface ParameterRange {
  min: number;
  max: number;
  description: string;
}

export interface InputConstraints {
  requiredEncoding: 'pcm16-wav';
  minFrames: number;
  maxChannels: number;
}

export interface ResearchConfiguration {
  id: string;
  name: string;
  version: string;
  schemaVersion: number;
  implementationVersion: string;
  inputConstraints: InputConstraints;
  operations: readonly OperationStep[];
  parameterRanges: Readonly<Record<string, ParameterRange>>;
  defaultVariationCount: number;
  seedStrategy: 'base-plus-index';
  /** Derives each variation's seed from the base seed. Fully determined. */
  variationSeed: (baseSeed: number, index: number) => number;
  /** Deterministic transform: identical arguments always yield identical bytes. */
  render: (inputBytes: Uint8Array, seed: number) => Uint8Array;
}

/** Parameters chosen for one variation, recorded in provenance. */
export interface DerivedParameters {
  fragmentCount: number;
  reversedFragments: number[];
  silenceFrames: number;
  gainNumerator: number;
  gainDenominator: number;
  order: number[];
}

function deriveParameters(seed: number, totalFrames: number): DerivedParameters {
  const rng = seededRandom(seed);
  const fragmentCount = 3 + Math.floor(rng() * 6);          // 3..8
  const fragments = fragmentEvenly(totalFrames, fragmentCount);
  const indices = fragments.map((_, i) => i);
  const order = shuffleWithSeed(indices, rng);
  const reversedFragments = order.filter(() => rng() < 0.4);
  const silenceFrames = Math.floor(rng() * 800);            // 0..799
  const gainNumerator = 6 + Math.floor(rng() * 5);          // 6..10
  return {
    fragmentCount: fragments.length, reversedFragments,
    silenceFrames, gainNumerator, gainDenominator: 10, order,
  };
}

/**
 * Fragment-level shaping only: fragmenting, reordering, selective reversal,
 * spacing and a per-fragment gain that decays across position. Unchanged since
 * 1.0.0 — this is what gives each variation its internal dynamic character,
 * and the gain-consistency refinement in 1.1.0 must not touch it.
 */
function renderVariation(audio: AudioBuffer, seed: number): AudioBuffer {
  const frames = audio.samples.length / audio.channels;
  const params = deriveParameters(seed, frames);
  const fragments = fragmentEvenly(frames, params.fragmentCount);
  const reversed = new Set(params.reversedFragments);
  const gap = silence(params.silenceFrames, audio.channels);

  const parts: Int16Array[] = [];
  params.order.forEach((fragmentIndex, position) => {
    const fragment = fragments[fragmentIndex];
    if (!fragment) return;
    let piece = sliceFragment(audio, fragment);
    if (reversed.has(fragmentIndex)) piece = reverseFrames(piece, audio.channels);
    // Gain shaping decays across positions, so ordering is audible.
    const numerator = Math.max(3, params.gainNumerator - position);
    piece = applyGain(piece, numerator, params.gainDenominator);
    parts.push(piece);
    if (position < params.order.length - 1 && gap.length > 0) parts.push(gap);
  });

  return { ...audio, samples: concatSamples(parts) };
}

// ---- Preview-level gain correction (1.1.0) ---------------------------------

/**
 * Shared listening-level target for every Preview, independent of anything
 * else in its set. Measured against the 1.0.0 reference corpus (RMS spread
 * 0.067–0.133, ~6 dB): this sits near the middle of that range, so the
 * correction narrows the spread symmetrically rather than dragging everything
 * toward one extreme.
 */
export const PREVIEW_TARGET_RMS = 0.09;

/**
 * Fraction of the distance to the target that is actually applied. A full
 * snap-to-target (1.0) made every Preview measure identically — every one at
 * exactly PREVIEW_TARGET_RMS, a flat 0 dB spread — which is explicitly not the
 * goal: overall level is meant to become CONSISTENT, not IDENTICAL. Pulling
 * only partway narrows the reference-corpus spread from 6.0 dB to roughly
 * 2 dB while every Preview still measures audibly differently from its
 * siblings.
 */
export const PREVIEW_GAIN_PULL_STRENGTH = 0.65;

/** Bounded both directions: preserves character, narrows the range. */
export const PREVIEW_GAIN_MAX_BOOST_DB = 4;
export const PREVIEW_GAIN_MAX_CUT_DB = 4;

/** Safety margin under full scale, applied after the target correction. */
export const PREVIEW_PEAK_CEILING = 0.97;

const dbToLinear = (db: number): number => 10 ** (db / 20);
const linearToDb = (ratio: number): number => 20 * Math.log10(ratio);

export interface PreviewGainMeasurement {
  peak: number;
  rms: number;
  correction: number;
  correctionDb: number;
  clipped: boolean;
}

/** Peak and RMS of a completed buffer, in the same units the correction targets. */
export function measurePreviewLevel(samples: Int16Array): { peak: number; rms: number } {
  let peak = 0;
  let sumSquares = 0;
  for (const s of samples) {
    const v = s / 32768;
    const a = Math.abs(v);
    if (a > peak) peak = a;
    sumSquares += v * v;
  }
  const rms = samples.length > 0 ? Math.sqrt(sumSquares / samples.length) : 0;
  return { peak, rms };
}

/**
 * One deterministic global gain factor for a completed Preview.
 *
 * A pure function of that Preview's own samples: never derived from sibling
 * Previews in the same set, so generating one Preview alone or as part of
 * eight produces identical bytes. Bounded in both directions, then re-checked
 * against a peak ceiling so the correction itself can never introduce
 * clipping — the fragment-level dynamics stay exactly as shaped, this only
 * scales the whole result once.
 */
export function computePreviewGainCorrection(samples: Int16Array): number {
  const { peak, rms } = measurePreviewLevel(samples);
  if (rms === 0 || peak === 0) return 1; // silence: nothing to correct, no division by zero

  // Move only part of the way toward the target, in dB (perceptual, not linear)
  // so a small ideal correction and a large one are pulled by the same
  // proportion of the ear's sense of loudness.
  const idealDb = linearToDb(PREVIEW_TARGET_RMS / rms);
  let appliedDb = idealDb * PREVIEW_GAIN_PULL_STRENGTH;
  appliedDb = Math.min(PREVIEW_GAIN_MAX_BOOST_DB, Math.max(-PREVIEW_GAIN_MAX_CUT_DB, appliedDb));
  let correction = dbToLinear(appliedDb);

  const projectedPeak = peak * correction;
  if (projectedPeak > PREVIEW_PEAK_CEILING) {
    correction = PREVIEW_PEAK_CEILING / peak;
  }
  return correction;
}

function applyPreviewGainCorrection(samples: Int16Array): { samples: Int16Array; correction: number } {
  const correction = computePreviewGainCorrection(samples);
  if (correction === 1) return { samples, correction };
  const out = new Int16Array(samples.length);
  for (let i = 0; i < samples.length; i++) {
    out[i] = Math.max(-32768, Math.min(32767, Math.round(samples[i]! * correction)));
  }
  return { samples: out, correction };
}

function renderVariationV1_1(audio: AudioBuffer, seed: number): AudioBuffer {
  const raw = renderVariation(audio, seed);
  const { samples } = applyPreviewGainCorrection(raw.samples);
  return { ...raw, samples };
}

// ---- Slice-boundary micro-fade (1.2.0) -------------------------------------

/**
 * Short deterministic fade around fragment/silence splice boundaries, to
 * remove the discontinuity clicks measured at those cut points without
 * smearing rhythm or shifting timing. Sample-rate independent in perceptual
 * duration: 5ms converts to ~221 frames at 44.1kHz, exactly 240 at 48kHz.
 */
export const PREVIEW_BOUNDARY_FADE_MS = 5;

export function fadeFramesForSampleRate(
  sampleRateHz: number, fadeMs: number = PREVIEW_BOUNDARY_FADE_MS,
): number {
  return Math.round((sampleRateHz * fadeMs) / 1000);
}

/**
 * Same fragment shaping and gain-consistency correction as 1.1.0, with one
 * addition in between: every non-silence piece fades out unless it is the
 * very last element of the Preview, and fades in unless it is the very first.
 * That single rule covers all three boundary shapes without special cases —
 * fragment-to-fragment fades both sides, fragment-to-silence fades only the
 * outgoing fragment (never the silence itself), silence-to-fragment fades
 * only the incoming fragment. The natural start and end of the whole Preview
 * are never faded: they are not artificial splices.
 */
function renderVariationV1_2(audio: AudioBuffer, seed: number): AudioBuffer {
  const frames = audio.samples.length / audio.channels;
  const params = deriveParameters(seed, frames);
  const fragments = fragmentEvenly(frames, params.fragmentCount);
  const reversed = new Set(params.reversedFragments);
  const gap = silence(params.silenceFrames, audio.channels);
  const configuredFade = fadeFramesForSampleRate(audio.sampleRate);

  const parts: Int16Array[] = [];
  const isGap: boolean[] = [];
  params.order.forEach((fragmentIndex, position) => {
    const fragment = fragments[fragmentIndex];
    if (!fragment) return;
    let piece = sliceFragment(audio, fragment);
    if (reversed.has(fragmentIndex)) piece = reverseFrames(piece, audio.channels);
    const numerator = Math.max(3, params.gainNumerator - position);
    piece = applyGain(piece, numerator, params.gainDenominator);
    parts.push(piece);
    isGap.push(false);
    if (position < params.order.length - 1 && gap.length > 0) {
      parts.push(gap);
      isGap.push(true);
    }
  });

  for (let i = 0; i < parts.length; i++) {
    if (isGap[i]) continue; // silence itself is never faded
    const fadeIn = i > 0 ? configuredFade : 0;
    const fadeOut = i < parts.length - 1 ? configuredFade : 0;
    if (fadeIn === 0 && fadeOut === 0) continue;
    parts[i] = applyBoundaryFade(parts[i]!, audio.channels, fadeIn, fadeOut);
  }

  const raw = { ...audio, samples: concatSamples(parts) };
  const { samples } = applyPreviewGainCorrection(raw.samples);
  return { ...raw, samples };
}

// ---- configurations ---------------------------------------------------------

export const FRAGMENT_EXPLORATION_V1: ResearchConfiguration = {
  id: 'fragment-exploration-v1',
  name: 'Fragment exploration',
  version: '1.0.0',
  schemaVersion: RESEARCH_CONFIGURATION_SCHEMA_VERSION,
  implementationVersion: '1.0.0',
  inputConstraints: { requiredEncoding: 'pcm16-wav', minFrames: 64, maxChannels: 2 },
  operations: [
    { operation: 'fragment', description: 'divide the input into deterministic fragments' },
    { operation: 'reorder', description: 'permute fragments using the variation seed' },
    { operation: 'reverse', description: 'reverse a seed-selected subset of fragments' },
    { operation: 'space', description: 'insert controlled silence between fragments' },
    { operation: 'gain', description: 'integer gain shaping decaying across positions' },
    { operation: 'reconstruct', description: 'rebuild a canonical PCM16 WAV result' },
  ],
  parameterRanges: {
    fragmentCount: { min: 3, max: 8, description: 'number of deterministic fragments' },
    silenceFrames: { min: 0, max: 799, description: 'frames of silence between fragments' },
    gainNumerator: { min: 3, max: 10, description: 'integer gain numerator over denominator 10' },
  },
  defaultVariationCount: 8,
  seedStrategy: 'base-plus-index',
  variationSeed: (baseSeed, index) => (baseSeed + index * 7919) >>> 0,
  render: (inputBytes, seed) => encodeWav(renderVariation(decodeWav(inputBytes), seed)),
};

/**
 * Same fragment shaping as 1.0.0, plus one deterministic Preview-level gain
 * correction applied after reconstruction. Narrows overall listening-level
 * spread across a Preview Set while preserving internal dynamics: no
 * compressor, no limiter, one measured global multiply, bounded and
 * clip-safe.
 */
export const FRAGMENT_EXPLORATION_V1_1: ResearchConfiguration = {
  id: 'fragment-exploration-v1',
  name: 'Fragment exploration',
  version: '1.1.0',
  schemaVersion: RESEARCH_CONFIGURATION_SCHEMA_VERSION,
  implementationVersion: '1.1.0',
  inputConstraints: { requiredEncoding: 'pcm16-wav', minFrames: 64, maxChannels: 2 },
  operations: [
    ...FRAGMENT_EXPLORATION_V1.operations,
    {
      operation: 'preview-gain-correction',
      description: 'one deterministic global gain factor toward a shared listening-level target, ' +
        'bounded and clip-safe, measured from this Preview alone',
    },
  ],
  parameterRanges: {
    ...FRAGMENT_EXPLORATION_V1.parameterRanges,
    previewGainCorrectionDb: {
      min: -PREVIEW_GAIN_MAX_CUT_DB, max: PREVIEW_GAIN_MAX_BOOST_DB,
      description: 'global correction applied once to the completed Preview',
    },
  },
  defaultVariationCount: 8,
  seedStrategy: 'base-plus-index',
  variationSeed: (baseSeed, index) => (baseSeed + index * 7919) >>> 0,
  render: (inputBytes, seed) => encodeWav(renderVariationV1_1(decodeWav(inputBytes), seed)),
};

/**
 * Same fragment shaping and Preview-level gain consistency as 1.1.0, plus
 * deterministic micro-fades at every splice boundary. Preserves the cut and
 * rearranged character — fades are a few hundred frames at most, an order of
 * magnitude shorter than the shortest fragment — while removing the
 * discontinuity clicks measured at fragment, reversal and silence boundaries.
 */
export const FRAGMENT_EXPLORATION_V1_2: ResearchConfiguration = {
  id: 'fragment-exploration-v1',
  name: 'Fragment exploration',
  version: '1.2.0',
  schemaVersion: RESEARCH_CONFIGURATION_SCHEMA_VERSION,
  implementationVersion: '1.2.0',
  inputConstraints: { requiredEncoding: 'pcm16-wav', minFrames: 64, maxChannels: 2 },
  operations: [
    ...FRAGMENT_EXPLORATION_V1.operations,
    {
      operation: 'boundary-fade',
      description: `deterministic ${PREVIEW_BOUNDARY_FADE_MS}ms linear fade at fragment and ` +
        'silence splice boundaries, capped for short fragments, to remove discontinuity clicks',
    },
    FRAGMENT_EXPLORATION_V1_1.operations[FRAGMENT_EXPLORATION_V1_1.operations.length - 1]!,
  ],
  parameterRanges: {
    ...FRAGMENT_EXPLORATION_V1_1.parameterRanges,
    boundaryFadeMs: {
      min: PREVIEW_BOUNDARY_FADE_MS, max: PREVIEW_BOUNDARY_FADE_MS,
      description: 'fixed micro-fade duration converted to frames at the source sample rate, ' +
        'capped at one quarter of the enclosing fragment',
    },
  },
  defaultVariationCount: 8,
  seedStrategy: 'base-plus-index',
  variationSeed: (baseSeed, index) => (baseSeed + index * 7919) >>> 0,
  render: (inputBytes, seed) => encodeWav(renderVariationV1_2(decodeWav(inputBytes), seed)),
};

/** New explorations default to the latest configuration version. */
export const DEFAULT_FRAGMENT_EXPLORATION = FRAGMENT_EXPLORATION_V1_2;

export const BUILT_IN_CONFIGURATIONS: readonly ResearchConfiguration[] = [
  FRAGMENT_EXPLORATION_V1, FRAGMENT_EXPLORATION_V1_1, FRAGMENT_EXPLORATION_V1_2,
];

const DEFAULT_VERSION_BY_ID = new Map<string, ResearchConfiguration>([
  [DEFAULT_FRAGMENT_EXPLORATION.id, DEFAULT_FRAGMENT_EXPLORATION],
]);

/**
 * Resolve a configuration by id, optionally pinned to an exact version.
 * Omitting version returns the current default — this is how new explorations
 * pick up 1.1.0 without call sites needing to know a version exists. An old
 * manifest that recorded "1.0.0" must always pass its version explicitly, so
 * replay resolves the exact configuration that produced it, not the default.
 */
export function configurationById(id: string, version?: string): ResearchConfiguration {
  const candidates = BUILT_IN_CONFIGURATIONS.filter((c) => c.id === id);
  if (candidates.length === 0) throw new Error(`unknown research configuration: ${id}`);
  if (version) {
    const exact = candidates.find((c) => c.version === version);
    if (!exact) throw new Error(`unknown research configuration version: ${id}@${version}`);
    return exact;
  }
  return DEFAULT_VERSION_BY_ID.get(id) ?? candidates[candidates.length - 1]!;
}

export function describeParameters(seed: number, totalFrames: number): DerivedParameters {
  return deriveParameters(seed, totalFrames);
}
