// Generated by build.mjs from src/web/lab.ts — do not edit directly.

// src/persistence/record-store.ts
var MAX_BATCH_MUTATIONS = 512;

// src/core/primitives.ts
var COLLECTIONS = {
  entities: "entities",
  relationships: "relationships",
  knowledge: "knowledge",
  transitions: "transitions",
  agents: "agents",
  meta: "meta"
};

// src/persistence/schema.ts
var SCHEMA_V1 = {
  version: 1,
  collections: Object.values(COLLECTIONS),
  indexes: [
    // Entities
    {
      name: "ent_by_role_lifecycle",
      collection: COLLECTIONS.entities,
      fields: ["role", "lifecycleState", "createdAt", "id"]
    },
    {
      name: "ent_by_content_hash",
      collection: COLLECTIONS.entities,
      fields: ["attributes.contentHash", "createdAt", "id"]
    },
    {
      name: "ent_by_type",
      collection: COLLECTIONS.entities,
      fields: ["type", "createdAt", "id"]
    },
    // Relationships (adjacency)
    {
      name: "rel_by_source",
      collection: COLLECTIONS.relationships,
      fields: ["source", "type", "createdAt", "id"]
    },
    {
      name: "rel_by_target",
      collection: COLLECTIONS.relationships,
      fields: ["target", "type", "createdAt", "id"]
    },
    // Knowledge
    {
      name: "kno_by_subject_stage",
      collection: COLLECTIONS.knowledge,
      fields: ["subject", "stage", "createdAt", "id"]
    },
    {
      name: "kno_by_subject_kind_agent",
      collection: COLLECTIONS.knowledge,
      fields: ["subject", "kind", "agentId", "agentVersion", "createdAt", "id"]
    },
    {
      name: "kno_by_supersedes",
      collection: COLLECTIONS.knowledge,
      fields: ["supersedes", "createdAt", "id"]
    },
    // Transitions
    {
      name: "tra_by_subject",
      collection: COLLECTIONS.transitions,
      fields: ["subject", "createdAt", "id"]
    },
    {
      name: "tra_by_idempotency",
      collection: COLLECTIONS.transitions,
      fields: ["idempotencyKey"],
      unique: true
    },
    // Agents
    {
      name: "agt_by_kind_name_version",
      collection: COLLECTIONS.agents,
      fields: ["kind", "name", "version"],
      unique: true
    }
  ]
};
function indexesFor(schema, collection) {
  return schema.indexes.filter((i) => i.collection === collection);
}

// src/core/errors.ts
var SpkError = class extends Error {
  code;
  constructor(code, message) {
    super(message);
    this.name = new.target.name;
    this.code = code;
  }
};
var UniquenessError = class extends SpkError {
  constructor(collection, index, detail) {
    super("UNIQUENESS", `unique index ${collection}.${index} violated: ${detail}`);
  }
};
var IntegrityError = class extends SpkError {
  constructor(detail) {
    super("INTEGRITY", detail);
  }
};
var BatchTooLargeError = class extends SpkError {
  constructor(size, max) {
    super("BATCH_TOO_LARGE", `batch of ${size} mutations exceeds bounded maximum ${max}`);
  }
};
var NotFoundError = class extends SpkError {
  constructor(collection, id) {
    super("NOT_FOUND", `${collection}/${id} not found`);
  }
};
var DomainRuleError = class extends SpkError {
  constructor(detail) {
    super("DOMAIN_RULE", detail);
  }
};
var KeyEncodingError = class extends SpkError {
  constructor(detail) {
    super("KEY_ENCODING", detail);
  }
};

// src/persistence/keys.ts
var TAG_NULL = 16;
var TAG_FALSE = 24;
var TAG_TRUE = 25;
var TAG_INT = 32;
var TAG_STR = 48;
var INT_OFFSET = 1n << 63n;
function encodeInt(value) {
  if (!Number.isInteger(value)) {
    throw new KeyEncodingError(
      `only integer numbers may be key components (got ${value}); timestamps must be numeric epoch milliseconds`
    );
  }
  if (!Number.isSafeInteger(value)) {
    throw new KeyEncodingError(`integer key component out of safe range: ${value}`);
  }
  const buf = Buffer.alloc(9);
  buf.writeUInt8(TAG_INT, 0);
  buf.writeBigUInt64BE(BigInt(value) + INT_OFFSET, 1);
  return buf;
}
function encodeString(value) {
  const raw = Buffer.from(value, "utf8");
  const out = [TAG_STR];
  for (const byte of raw) {
    if (byte === 0) {
      out.push(0, 255);
    } else {
      out.push(byte);
    }
  }
  out.push(0, 0);
  return Buffer.from(out);
}
function encodeKey(tuple) {
  const parts = [];
  for (const component of tuple) {
    if (component === null) {
      parts.push(Buffer.from([TAG_NULL]));
    } else if (typeof component === "boolean") {
      parts.push(Buffer.from([component ? TAG_TRUE : TAG_FALSE]));
    } else if (typeof component === "number") {
      parts.push(encodeInt(component));
    } else if (typeof component === "string") {
      parts.push(encodeString(component));
    } else {
      throw new KeyEncodingError(`unsupported key component type: ${typeof component}`);
    }
  }
  return Buffer.concat(parts);
}
function decodeKey(buf) {
  const out = [];
  let i = 0;
  while (i < buf.length) {
    const tag = buf[i];
    i += 1;
    if (tag === TAG_NULL) {
      out.push(null);
    } else if (tag === TAG_FALSE) {
      out.push(false);
    } else if (tag === TAG_TRUE) {
      out.push(true);
    } else if (tag === TAG_INT) {
      const raw = buf.readBigUInt64BE(i);
      i += 8;
      out.push(Number(raw - INT_OFFSET));
    } else if (tag === TAG_STR) {
      const bytes = [];
      for (; ; ) {
        if (i >= buf.length) throw new KeyEncodingError("truncated string component");
        const b = buf[i];
        if (b === 0) {
          const next = buf[i + 1];
          if (next === 0) {
            i += 2;
            break;
          }
          if (next === 255) {
            bytes.push(0);
            i += 2;
            continue;
          }
          throw new KeyEncodingError("invalid escape sequence in string component");
        }
        bytes.push(b);
        i += 1;
      }
      out.push(Buffer.from(bytes).toString("utf8"));
    } else {
      throw new KeyEncodingError(`unknown key tag 0x${tag.toString(16)}`);
    }
  }
  return out;
}
function prefixUpperBound(prefix) {
  const out = Buffer.from(prefix);
  for (let i = out.length - 1; i >= 0; i--) {
    if (out[i] < 255) {
      out[i] = out[i] + 1;
      return out.subarray(0, i + 1);
    }
  }
  return null;
}

// src/adapters/indexeddb/record-store.ts
var RECORD_STORE_SUFFIX = "";
var INDEX_STORE = "__index_entries";
var META_STORE = "__meta";
function request(req) {
  return new Promise((resolve, reject) => {
    req.onsuccess = () => resolve(req.result);
    req.onerror = () => reject(req.error ?? new Error("IndexedDB request failed"));
  });
}
function transactionDone(tx) {
  return new Promise((resolve, reject) => {
    tx.oncomplete = () => resolve();
    tx.onerror = () => reject(tx.error ?? new Error("IndexedDB transaction failed"));
    tx.onabort = () => reject(tx.error ?? new Error("IndexedDB transaction aborted"));
  });
}
function indexEntryKey(collection, index, key, id) {
  const head = encodeKey([collection, index]);
  const tail = encodeKey([id]);
  const out = new Uint8Array(head.length + key.length + tail.length + 1);
  out.set(head, 0);
  out.set(key, head.length);
  out[head.length + key.length] = 0;
  out.set(tail, head.length + key.length + 1);
  return out;
}
function scopePrefix(collection, index) {
  return new Uint8Array(encodeKey([collection, index]));
}
function concatBytes(a, b) {
  const out = new Uint8Array(a.length + b.length);
  out.set(a, 0);
  out.set(b, a.length);
  return out;
}
var IndexedDbRecordStore = class _IndexedDbRecordStore {
  #db;
  #schema;
  constructor(db, schema) {
    this.#db = db;
    this.#schema = schema;
  }
  static async open(databaseName, schema, factory) {
    const idb = factory ?? globalThis.indexedDB;
    if (!idb) throw new Error("IndexedDB is not available in this environment");
    const req = idb.open(databaseName, schema.version);
    req.onupgradeneeded = () => {
      const db2 = req.result;
      for (const collection of schema.collections) {
        if (!db2.objectStoreNames.contains(collection + RECORD_STORE_SUFFIX)) {
          db2.createObjectStore(collection + RECORD_STORE_SUFFIX, { keyPath: "id" });
        }
      }
      if (!db2.objectStoreNames.contains(INDEX_STORE)) db2.createObjectStore(INDEX_STORE);
      if (!db2.objectStoreNames.contains(META_STORE)) db2.createObjectStore(META_STORE);
    };
    const db = await request(req);
    return new _IndexedDbRecordStore(db, schema);
  }
  // ---- internals -----------------------------------------------------------
  #extract(record, path) {
    let cur = record;
    for (const part of path.split(".")) {
      if (cur === null || cur === void 0 || typeof cur !== "object") return null;
      cur = cur[part];
    }
    if (cur === void 0 || cur === null) return null;
    if (typeof cur === "string" || typeof cur === "number" || typeof cur === "boolean") return cur;
    return String(cur);
  }
  #indexKey(decl, record) {
    return new Uint8Array(encodeKey(decl.fields.map((f) => this.#extract(record, f))));
  }
  async #entriesForRecord(collection, id) {
    const tx = this.#db.transaction(INDEX_STORE, "readonly");
    const store = tx.objectStore(INDEX_STORE);
    const out = [];
    for (const decl of indexesFor(this.#schema, collection)) {
      const prefix = scopePrefix(collection, decl.name);
      const upper = prefixUpperBound(Buffer.from(prefix));
      const range = upper ? IDBKeyRange.bound(prefix, new Uint8Array(upper), false, true) : IDBKeyRange.lowerBound(prefix);
      const keys = await request(store.getAllKeys(range));
      const values = await request(
        store.getAll(range)
      );
      keys.forEach((k, i) => {
        if (values[i]?.recordId === id) out.push(new Uint8Array(k));
      });
    }
    return out;
  }
  async #uniquenessConflict(collection, decl, key, id) {
    const tx = this.#db.transaction(INDEX_STORE, "readonly");
    const store = tx.objectStore(INDEX_STORE);
    const scoped = concatBytes(scopePrefix(collection, decl.name), key);
    const upper = prefixUpperBound(Buffer.from(scoped));
    const range = upper ? IDBKeyRange.bound(scoped, new Uint8Array(upper), false, true) : IDBKeyRange.lowerBound(scoped);
    const values = await request(store.getAll(range));
    const clash = values.find((v) => v.recordId !== id);
    return clash ? clash.recordId : null;
  }
  // ---- portable contract ---------------------------------------------------
  async get(collection, id) {
    const tx = this.#db.transaction(collection, "readonly");
    const result = await request(tx.objectStore(collection).get(id));
    return result ?? null;
  }
  async getMany(collection, ids) {
    const tx = this.#db.transaction(collection, "readonly");
    const store = tx.objectStore(collection);
    const out = [];
    for (const id of ids) {
      out.push(await request(store.get(id)) ?? null);
    }
    return out;
  }
  async commit(batch) {
    if (batch.length > MAX_BATCH_MUTATIONS) {
      throw new BatchTooLargeError(batch.length, MAX_BATCH_MUTATIONS);
    }
    if (batch.length === 0) return;
    const plan = { puts: [], deletes: [], indexPuts: [], indexDeletes: [] };
    for (const m of batch) {
      const collection = m.collection;
      const id = m.op === "put" ? m.record.id : m.id;
      for (const key of await this.#entriesForRecord(collection, id)) plan.indexDeletes.push(key);
      if (m.op === "put") {
        for (const decl of indexesFor(this.#schema, collection)) {
          const key = this.#indexKey(decl, m.record);
          if (decl.unique) {
            const clash = await this.#uniquenessConflict(collection, decl, key, m.record.id);
            if (clash) {
              throw new UniquenessError(collection, decl.name, `key already held by ${clash}`);
            }
          }
          plan.indexPuts.push({
            key: indexEntryKey(collection, decl.name, key, m.record.id),
            recordId: m.record.id,
            keyBytes: key
          });
        }
        plan.puts.push({ collection, record: m.record });
      } else {
        plan.deletes.push({ collection, id });
      }
    }
    const stores = [.../* @__PURE__ */ new Set([
      ...plan.puts.map((p) => p.collection),
      ...plan.deletes.map((d) => d.collection),
      INDEX_STORE
    ])];
    const tx = this.#db.transaction(stores, "readwrite");
    const indexStore = tx.objectStore(INDEX_STORE);
    for (const key of plan.indexDeletes) indexStore.delete(key);
    for (const p of plan.puts) tx.objectStore(p.collection).put(p.record);
    for (const d of plan.deletes) tx.objectStore(d.collection).delete(d.id);
    for (const e of plan.indexPuts) {
      indexStore.put({ recordId: e.recordId, keyBytes: e.keyBytes }, e.key);
    }
    await transactionDone(tx);
  }
  async lookup(query) {
    const decl = this.#schema.indexes.find(
      (i) => i.name === query.index && i.collection === query.collection
    );
    if (!decl) throw new Error(`unknown index ${query.collection}.${query.index}`);
    const scope = scopePrefix(query.collection, decl.name);
    let lower = scope;
    let upper = (() => {
      const u = prefixUpperBound(Buffer.from(scope));
      return u ? new Uint8Array(u) : null;
    })();
    const scoped = (tuple) => concatBytes(scope, new Uint8Array(encodeKey(tuple)));
    if (query.eq || query.prefix) {
      const base = scoped(query.eq ?? query.prefix);
      lower = base;
      const u = prefixUpperBound(Buffer.from(base));
      upper = u ? new Uint8Array(u) : null;
    } else if (query.range) {
      if (query.range.gte) lower = scoped(query.range.gte);
      if (query.range.lt) upper = scoped(query.range.lt);
    }
    if (query.after) {
      const bump = concatBytes(scoped(query.after), new Uint8Array([1]));
      if (Buffer.compare(Buffer.from(bump), Buffer.from(lower)) > 0) lower = bump;
    }
    const range = upper ? IDBKeyRange.bound(lower, upper, false, true) : IDBKeyRange.lowerBound(lower);
    const tx = this.#db.transaction(INDEX_STORE, "readonly");
    const store = tx.objectStore(INDEX_STORE);
    const values = await request(store.getAll(range, query.limit));
    const items = [];
    const recordTx = this.#db.transaction(query.collection, "readonly");
    const recordStore = recordTx.objectStore(query.collection);
    for (const v of values) {
      const rec = await request(recordStore.get(v.recordId));
      if (rec) items.push(rec);
    }
    let nextAfter = null;
    if (values.length === query.limit && values.length > 0) {
      const lastKey = values[values.length - 1].keyBytes;
      nextAfter = decodeKey(Buffer.from(
        lastKey instanceof Uint8Array ? lastKey : new Uint8Array(lastKey)
      ));
    }
    return { items, nextAfter };
  }
  #adjacency(index, q) {
    const prefix = q.type ? [q.nodeId, q.type] : [q.nodeId];
    return this.lookup({
      collection: "relationships",
      index,
      prefix,
      after: q.after,
      limit: q.limit
    });
  }
  adjacencyBySource(q) {
    return this.#adjacency("rel_by_source", q);
  }
  adjacencyByTarget(q) {
    return this.#adjacency("rel_by_target", q);
  }
  async schemaVersion() {
    const tx = this.#db.transaction(META_STORE, "readonly");
    const v = await request(tx.objectStore(META_STORE).get("schemaVersion"));
    return v ?? 0;
  }
  async setSchemaVersion(version) {
    const tx = this.#db.transaction(META_STORE, "readwrite");
    tx.objectStore(META_STORE).put(version, "schemaVersion");
    await transactionDone(tx);
  }
  async scan(collection, after, limit) {
    const tx = this.#db.transaction(collection, "readonly");
    const range = after === null ? void 0 : IDBKeyRange.lowerBound(after, true);
    const items = await request(
      tx.objectStore(collection).getAll(range, limit)
    );
    return {
      items,
      nextAfter: items.length === limit && items.length > 0 ? [items[items.length - 1].id] : null
    };
  }
  async close() {
    this.#db.close();
  }
};

// src/core/sha256.ts
var K = new Uint32Array([
  1116352408,
  1899447441,
  3049323471,
  3921009573,
  961987163,
  1508970993,
  2453635748,
  2870763221,
  3624381080,
  310598401,
  607225278,
  1426881987,
  1925078388,
  2162078206,
  2614888103,
  3248222580,
  3835390401,
  4022224774,
  264347078,
  604807628,
  770255983,
  1249150122,
  1555081692,
  1996064986,
  2554220882,
  2821834349,
  2952996808,
  3210313671,
  3336571891,
  3584528711,
  113926993,
  338241895,
  666307205,
  773529912,
  1294757372,
  1396182291,
  1695183700,
  1986661051,
  2177026350,
  2456956037,
  2730485921,
  2820302411,
  3259730800,
  3345764771,
  3516065817,
  3600352804,
  4094571909,
  275423344,
  430227734,
  506948616,
  659060556,
  883997877,
  958139571,
  1322822218,
  1537002063,
  1747873779,
  1955562222,
  2024104815,
  2227730452,
  2361852424,
  2428436474,
  2756734187,
  3204031479,
  3329325298
]);
var rotr = (x, n) => x >>> n | x << 32 - n;
function sha256(input) {
  const h = new Uint32Array([
    1779033703,
    3144134277,
    1013904242,
    2773480762,
    1359893119,
    2600822924,
    528734635,
    1541459225
  ]);
  const bitLength = input.length * 8;
  const paddedLength = input.length + 9 + 63 >> 6 << 6;
  const data = new Uint8Array(paddedLength);
  data.set(input);
  data[input.length] = 128;
  const view = new DataView(data.buffer);
  view.setUint32(paddedLength - 8, Math.floor(bitLength / 4294967296));
  view.setUint32(paddedLength - 4, bitLength >>> 0);
  const w = new Uint32Array(64);
  for (let offset = 0; offset < paddedLength; offset += 64) {
    for (let i = 0; i < 16; i++) w[i] = view.getUint32(offset + i * 4);
    for (let i = 16; i < 64; i++) {
      const s0 = rotr(w[i - 15], 7) ^ rotr(w[i - 15], 18) ^ w[i - 15] >>> 3;
      const s1 = rotr(w[i - 2], 17) ^ rotr(w[i - 2], 19) ^ w[i - 2] >>> 10;
      w[i] = w[i - 16] + s0 + w[i - 7] + s1 >>> 0;
    }
    let [a, b, c, d, e, f, g, hh] = [h[0], h[1], h[2], h[3], h[4], h[5], h[6], h[7]];
    for (let i = 0; i < 64; i++) {
      const S1 = rotr(e, 6) ^ rotr(e, 11) ^ rotr(e, 25);
      const ch = e & f ^ ~e & g;
      const temp1 = hh + S1 + ch + K[i] + w[i] >>> 0;
      const S0 = rotr(a, 2) ^ rotr(a, 13) ^ rotr(a, 22);
      const maj = a & b ^ a & c ^ b & c;
      const temp2 = S0 + maj >>> 0;
      hh = g;
      g = f;
      f = e;
      e = d + temp1 >>> 0;
      d = c;
      c = b;
      b = a;
      a = temp1 + temp2 >>> 0;
    }
    h[0] = h[0] + a >>> 0;
    h[1] = h[1] + b >>> 0;
    h[2] = h[2] + c >>> 0;
    h[3] = h[3] + d >>> 0;
    h[4] = h[4] + e >>> 0;
    h[5] = h[5] + f >>> 0;
    h[6] = h[6] + g >>> 0;
    h[7] = h[7] + hh >>> 0;
  }
  const out = new Uint8Array(32);
  const outView = new DataView(out.buffer);
  for (let i = 0; i < 8; i++) outView.setUint32(i * 4, h[i]);
  return out;
}
function sha256Hex(input) {
  let hex = "";
  for (const byte of sha256(input)) hex += byte.toString(16).padStart(2, "0");
  return hex;
}
var TEXT = new TextEncoder();
function sha256HexOfStrings(parts) {
  const encoded = parts.map((p) => TEXT.encode(p));
  let total = 0;
  for (const e of encoded) total += e.length + 1;
  const buf = new Uint8Array(total);
  let offset = 0;
  for (const e of encoded) {
    buf.set(e, offset);
    offset += e.length;
    buf[offset] = 0;
    offset += 1;
  }
  return sha256Hex(buf);
}
function uuidV4() {
  const bytes = new Uint8Array(16);
  const webcrypto = globalThis.crypto;
  if (webcrypto?.getRandomValues) webcrypto.getRandomValues(bytes);
  else for (let i = 0; i < 16; i++) bytes[i] = Math.floor(Math.random() * 256);
  bytes[6] = bytes[6] & 15 | 64;
  bytes[8] = bytes[8] & 63 | 128;
  const hex = [...bytes].map((b) => b.toString(16).padStart(2, "0")).join("");
  return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-${hex.slice(12, 16)}-${hex.slice(16, 20)}-${hex.slice(20)}`;
}

// src/core/ids.ts
function newUuid() {
  return uuidV4();
}
function idempotencyKey(...parts) {
  return "ik_" + sha256HexOfStrings(parts).slice(0, 32);
}
function contentHash(bytes) {
  return sha256Hex(bytes);
}

// src/adapters/indexeddb/content-store.ts
var STORE = "content";
function request2(req) {
  return new Promise((resolve, reject) => {
    req.onsuccess = () => resolve(req.result);
    req.onerror = () => reject(req.error ?? new Error("IndexedDB request failed"));
  });
}
function transactionDone2(tx) {
  return new Promise((resolve, reject) => {
    tx.oncomplete = () => resolve();
    tx.onerror = () => reject(tx.error ?? new Error("transaction failed"));
    tx.onabort = () => reject(tx.error ?? new Error("transaction aborted"));
  });
}
var IndexedDbContentStore = class _IndexedDbContentStore {
  #db;
  constructor(db) {
    this.#db = db;
  }
  static async open(databaseName, factory) {
    const idb = factory ?? globalThis.indexedDB;
    if (!idb) throw new Error("IndexedDB is not available in this environment");
    const req = idb.open(databaseName, 1);
    req.onupgradeneeded = () => {
      const db = req.result;
      if (!db.objectStoreNames.contains(STORE)) db.createObjectStore(STORE);
    };
    return new _IndexedDbContentStore(await request2(req));
  }
  async put(bytes) {
    const hash = contentHash(bytes);
    const existing = await this.stat(hash);
    if (existing) return existing;
    const tx = this.#db.transaction(STORE, "readwrite");
    tx.objectStore(STORE).put(bytes.slice(), hash);
    await transactionDone2(tx);
    return { hash, size: bytes.byteLength };
  }
  async get(hash) {
    const tx = this.#db.transaction(STORE, "readonly");
    const v = await request2(tx.objectStore(STORE).get(hash));
    return v ? new Uint8Array(v) : null;
  }
  async has(hash) {
    return await this.stat(hash) !== null;
  }
  async stat(hash) {
    const bytes = await this.get(hash);
    return bytes ? { hash, size: bytes.byteLength } : null;
  }
  async list() {
    const tx = this.#db.transaction(STORE, "readonly");
    const keys = await request2(tx.objectStore(STORE).getAllKeys());
    return keys.map(String).sort();
  }
  /** Maintenance only: garbage-collect orphaned blobs. Never on a domain path. */
  async remove(hash) {
    const tx = this.#db.transaction(STORE, "readwrite");
    tx.objectStore(STORE).delete(hash);
    await transactionDone2(tx);
  }
  async close() {
    this.#db.close();
  }
};

// src/registries/data-registry.ts
var DataRegistry = class {
  #entities = /* @__PURE__ */ new Map();
  #relationships = /* @__PURE__ */ new Map();
  #knowledge = /* @__PURE__ */ new Map();
  #roles = /* @__PURE__ */ new Set();
  registerEntityType(def) {
    if (this.#entities.has(def.type)) throw new DomainRuleError(`entity type already registered: ${def.type}`);
    this.#entities.set(def.type, def);
    this.#roles.add(def.role);
  }
  registerRelationshipType(def) {
    if (this.#relationships.has(def.type)) throw new DomainRuleError(`relationship type already registered: ${def.type}`);
    this.#relationships.set(def.type, def);
  }
  registerKnowledgeKind(def) {
    if (this.#knowledge.has(def.kind)) throw new DomainRuleError(`knowledge kind already registered: ${def.kind}`);
    this.#knowledge.set(def.kind, def);
  }
  entityType(type) {
    const d = this.#entities.get(type);
    if (!d) throw new DomainRuleError(`unregistered entity type: ${type}`);
    return d;
  }
  relationshipType(type) {
    const d = this.#relationships.get(type);
    if (!d) throw new DomainRuleError(`unregistered relationship type: ${type}`);
    return d;
  }
  knowledgeKind(kind) {
    const d = this.#knowledge.get(kind);
    if (!d) throw new DomainRuleError(`unregistered knowledge kind: ${kind}`);
    return d;
  }
  roles() {
    return [...this.#roles];
  }
  assertTransitionAllowed(type, from, to) {
    const def = this.entityType(type);
    const allowed = def.allowedTransitions[from] ?? [];
    if (!allowed.includes(to)) {
      throw new DomainRuleError(`lifecycle transition ${from} -> ${to} not allowed for ${type}`);
    }
  }
};

// src/domain/alchemy/vocabulary.ts
var ROLE_MATERIAL = "material";
var ROLE_RESEARCH = "research";
var TYPE_AUDIO_MATERIAL = "audio-material";
var TYPE_RESEARCH_INTENT = "research-intent";
var TYPE_EXPERIMENT = "experiment";
var LIFECYCLE = {
  retained: "retained",
  promoted: "promoted",
  rejected: "rejected"
};
var REL = {
  derivedFrom: "derived_from",
  producedByExperiment: "produced_by_experiment",
  outputOf: "output_of",
  inputTo: "input_to",
  investigatesIntent: "investigates_intent",
  supersedes: "supersedes"
};
var KNOWLEDGE_KIND = {
  physicalAnalysis: "physical-analysis",
  curatedConclusion: "curated-conclusion"
};
var TRANSITION_KIND = {
  import: "import",
  retain: "retain",
  promote: "promote",
  reject: "reject"
};
function registerAlchemyVocabulary(data, view) {
  data.registerEntityType({
    type: TYPE_AUDIO_MATERIAL,
    role: ROLE_MATERIAL,
    lifecycleStates: Object.values(LIFECYCLE),
    initialState: LIFECYCLE.retained,
    allowedTransitions: {
      [LIFECYCLE.retained]: [LIFECYCLE.promoted, LIFECYCLE.rejected],
      [LIFECYCLE.promoted]: [LIFECYCLE.rejected],
      [LIFECYCLE.rejected]: [LIFECYCLE.promoted]
    },
    validate: (attributes) => {
      if (typeof attributes.contentHash !== "string" || attributes.contentHash.length === 0) {
        throw new Error("audio-material requires a contentHash attribute");
      }
    }
  });
  data.registerEntityType({
    type: TYPE_RESEARCH_INTENT,
    role: ROLE_RESEARCH,
    lifecycleStates: ["active", "closed"],
    initialState: "active",
    allowedTransitions: { active: ["closed"], closed: ["active"] }
  });
  data.registerEntityType({
    type: TYPE_EXPERIMENT,
    role: ROLE_RESEARCH,
    lifecycleStates: ["recorded"],
    initialState: "recorded",
    allowedTransitions: { recorded: [] }
  });
  data.registerRelationshipType({
    type: REL.derivedFrom,
    sourceTypes: [TYPE_AUDIO_MATERIAL],
    targetTypes: [TYPE_AUDIO_MATERIAL]
  });
  data.registerRelationshipType({
    type: REL.producedByExperiment,
    sourceTypes: [TYPE_AUDIO_MATERIAL],
    targetTypes: [TYPE_EXPERIMENT]
  });
  data.registerRelationshipType({
    type: REL.outputOf,
    sourceTypes: [TYPE_AUDIO_MATERIAL],
    targetTypes: [TYPE_EXPERIMENT]
  });
  data.registerRelationshipType({
    type: REL.inputTo,
    sourceTypes: [TYPE_AUDIO_MATERIAL],
    targetTypes: [TYPE_EXPERIMENT]
  });
  data.registerRelationshipType({
    type: REL.investigatesIntent,
    sourceTypes: [TYPE_EXPERIMENT],
    targetTypes: [TYPE_RESEARCH_INTENT]
  });
  data.registerRelationshipType({ type: REL.supersedes, sourceTypes: "*", targetTypes: "*" });
  data.registerKnowledgeKind({
    kind: KNOWLEDGE_KIND.physicalAnalysis,
    allowedStages: ["observation", "deprecated"]
  });
  data.registerKnowledgeKind({
    kind: KNOWLEDGE_KIND.curatedConclusion,
    allowedStages: ["hypothesis", "validated", "canon", "deprecated"]
  });
  view?.register(TYPE_AUDIO_MATERIAL, { label: "Material", group: "Inventory" });
  view?.register(TYPE_RESEARCH_INTENT, { label: "Research Intent", group: "Research" });
  view?.register(TYPE_EXPERIMENT, { label: "Experiment", group: "Research" });
}

// src/audio/wav.ts
var CANONICAL_HEADER_BYTES = 44;
function encodeWav(audio) {
  const dataBytes = audio.samples.length * 2;
  const buf = Buffer.alloc(CANONICAL_HEADER_BYTES + dataBytes);
  buf.write("RIFF", 0, "ascii");
  buf.writeUInt32LE(36 + dataBytes, 4);
  buf.write("WAVE", 8, "ascii");
  buf.write("fmt ", 12, "ascii");
  buf.writeUInt32LE(16, 16);
  buf.writeUInt16LE(1, 20);
  buf.writeUInt16LE(audio.channels, 22);
  buf.writeUInt32LE(audio.sampleRate, 24);
  buf.writeUInt32LE(audio.sampleRate * audio.channels * 2, 28);
  buf.writeUInt16LE(audio.channels * 2, 32);
  buf.writeUInt16LE(16, 34);
  buf.write("data", 36, "ascii");
  buf.writeUInt32LE(dataBytes, 40);
  for (let i = 0; i < audio.samples.length; i++) {
    buf.writeInt16LE(audio.samples[i], CANONICAL_HEADER_BYTES + i * 2);
  }
  return new Uint8Array(buf);
}
function decodeWav(bytes) {
  const buf = Buffer.from(bytes.buffer, bytes.byteOffset, bytes.byteLength);
  if (buf.length < 12 || buf.toString("ascii", 0, 4) !== "RIFF" || buf.toString("ascii", 8, 12) !== "WAVE") {
    throw new Error("not a RIFF/WAVE stream");
  }
  let offset = 12;
  let sampleRate = 0, channels = 0, bitsPerSample = 0;
  let samples = null;
  while (offset + 8 <= buf.length) {
    const id = buf.toString("ascii", offset, offset + 4);
    const size = buf.readUInt32LE(offset + 4);
    const body = offset + 8;
    if (id === "fmt ") {
      channels = buf.readUInt16LE(body + 2);
      sampleRate = buf.readUInt32LE(body + 4);
      bitsPerSample = buf.readUInt16LE(body + 14);
    } else if (id === "data") {
      const count = Math.floor(size / 2);
      const out = new Int16Array(count);
      for (let i = 0; i < count; i++) out[i] = buf.readInt16LE(body + i * 2);
      samples = out;
    }
    offset = body + size + size % 2;
  }
  if (!samples || bitsPerSample !== 16) throw new Error("unsupported WAV: expected PCM16 data");
  return { sampleRate, channels, samples };
}

// src/audio/analyzer.ts
var ANALYSIS_SCHEMA_VERSION = 1;
var round = (n, places = 6) => {
  const f = 10 ** places;
  return Number.isFinite(n) ? Math.round(n * f) / f : 0;
};
function basicMetrics(audio) {
  const { samples, sampleRate, channels } = audio;
  const frames = channels > 0 ? samples.length / channels : 0;
  let peak = 0, sumSquares = 0, crossings = 0;
  let previous = 0;
  for (let i = 0; i < samples.length; i++) {
    const v = samples[i] / 32768;
    const a = Math.abs(v);
    if (a > peak) peak = a;
    sumSquares += v * v;
    if (i % channels === 0) {
      if (previous < 0 && v >= 0 || previous > 0 && v <= 0) crossings += 1;
      previous = v;
    }
  }
  const rms = samples.length > 0 ? Math.sqrt(sumSquares / samples.length) : 0;
  return {
    durationSeconds: round(sampleRate > 0 ? frames / sampleRate : 0),
    sampleRate,
    channels,
    frameCount: frames,
    peak: round(peak),
    rms: round(rms),
    zeroCrossingRate: round(frames > 0 ? crossings / frames : 0)
  };
}
function fftMagnitudes(input) {
  const n = input.length;
  const re = Float64Array.from(input);
  const im = new Float64Array(n);
  for (let i = 1, j = 0; i < n; i++) {
    let bit = n >> 1;
    for (; j & bit; bit >>= 1) j ^= bit;
    j ^= bit;
    if (i < j) {
      [re[i], re[j]] = [re[j], re[i]];
      [im[i], im[j]] = [im[j], im[i]];
    }
  }
  for (let len = 2; len <= n; len <<= 1) {
    const ang = -2 * Math.PI / len;
    for (let i = 0; i < n; i += len) {
      for (let k = 0; k < len / 2; k++) {
        const wr = Math.cos(ang * k), wi = Math.sin(ang * k);
        const ur = re[i + k], ui = im[i + k];
        const vr = re[i + k + len / 2] * wr - im[i + k + len / 2] * wi;
        const vi = re[i + k + len / 2] * wi + im[i + k + len / 2] * wr;
        re[i + k] = ur + vr;
        im[i + k] = ui + vi;
        re[i + k + len / 2] = ur - vr;
        im[i + k + len / 2] = ui - vi;
      }
    }
  }
  const mags = new Float64Array(n / 2);
  for (let i = 0; i < n / 2; i++) mags[i] = Math.hypot(re[i], im[i]);
  return mags;
}
function spectralCentroid(audio) {
  const N = 1024;
  const mono = new Float64Array(N);
  const { samples, channels } = audio;
  for (let f = 0; f < N; f++) {
    let acc = 0;
    for (let c = 0; c < channels; c++) acc += samples[f * channels + c] ?? 0;
    const w = 0.5 * (1 - Math.cos(2 * Math.PI * f / (N - 1)));
    mono[f] = acc / channels / 32768 * w;
  }
  const mags = fftMagnitudes(mono);
  let num = 0, den = 0;
  for (let k = 0; k < mags.length; k++) {
    const freq = k * audio.sampleRate / N;
    num += freq * mags[k];
    den += mags[k];
  }
  return den > 0 ? num / den : 0;
}
var ANALYZER_V1 = {
  name: "physical-analyzer",
  version: "1.0.0",
  metrics: ["durationSeconds", "sampleRate", "channels", "frameCount", "peak", "rms", "zeroCrossingRate"],
  run: (audio) => basicMetrics(audio)
};
var ANALYZER_V2 = {
  name: "physical-analyzer",
  version: "2.0.0",
  metrics: [...ANALYZER_V1.metrics, "spectralCentroidHz", "transientEstimate"],
  run: (audio) => {
    const base = basicMetrics(audio);
    const { samples, channels } = audio;
    let maxJump = 0;
    for (let i = channels; i < samples.length; i += channels) {
      maxJump = Math.max(maxJump, Math.abs(samples[i] - samples[i - channels]) / 32768);
    }
    return {
      ...base,
      spectralCentroidHz: round(spectralCentroid(audio), 3),
      transientEstimate: round(maxJump)
    };
  }
};
function analyzeBytes(analyzer, bytes) {
  return analyzer.run(decodeWav(bytes));
}

// src/audio/experiment.ts
var IMPLEMENTATION_VERSION = "1.0.0";
function reverse(audio) {
  const { samples, channels } = audio;
  const frames = samples.length / channels;
  const out = new Int16Array(samples.length);
  for (let f = 0; f < frames; f++) {
    const src = (frames - 1 - f) * channels;
    for (let c = 0; c < channels; c++) out[f * channels + c] = samples[src + c];
  }
  return { ...audio, samples: out };
}
function trim(audio, params) {
  const { samples, channels } = audio;
  const frames = samples.length / channels;
  const start = Math.max(0, Math.min(frames, params.startFrame ?? 0));
  const end = Math.max(start, Math.min(frames, params.endFrame ?? frames));
  return { ...audio, samples: samples.slice(start * channels, end * channels) };
}
function gain(audio, params) {
  const num = params.gainNumerator ?? 1;
  const den = params.gainDenominator ?? 1;
  const out = new Int16Array(audio.samples.length);
  for (let i = 0; i < audio.samples.length; i++) {
    const scaled = Math.trunc(audio.samples[i] * num / den);
    out[i] = Math.max(-32768, Math.min(32767, scaled));
  }
  return { ...audio, samples: out };
}
function applyOperation(operation, inputBytes, params = {}) {
  const audio = decodeWav(inputBytes);
  let result;
  switch (operation) {
    case "reverse":
      result = reverse(audio);
      break;
    case "trim":
      result = trim(audio, params);
      break;
    case "gain":
      result = gain(audio, params);
      break;
    default:
      throw new Error(`unknown operation: ${operation}`);
  }
  return encodeWav(result);
}

// src/audio/operations.ts
function seededRandom(seed) {
  let a = seed >>> 0;
  return () => {
    a = a + 1831565813 >>> 0;
    let t = a;
    t = Math.imul(t ^ t >>> 15, t | 1);
    t ^= t + Math.imul(t ^ t >>> 7, t | 61);
    return ((t ^ t >>> 14) >>> 0) / 4294967296;
  };
}
function fragmentEvenly(totalFrames, count) {
  const n = Math.max(1, Math.min(count, totalFrames));
  const size = Math.floor(totalFrames / n);
  const out = [];
  for (let i = 0; i < n; i++) {
    out.push({ startFrame: i * size, endFrame: i === n - 1 ? totalFrames : (i + 1) * size });
  }
  return out;
}
function shuffleWithSeed(items, rng) {
  const out = [...items];
  for (let i = out.length - 1; i > 0; i--) {
    const j = Math.floor(rng() * (i + 1));
    [out[i], out[j]] = [out[j], out[i]];
  }
  return out;
}
function sliceFragment(audio, f) {
  return audio.samples.slice(f.startFrame * audio.channels, f.endFrame * audio.channels);
}
function reverseFrames(samples, channels) {
  const frames = samples.length / channels;
  const out = new Int16Array(samples.length);
  for (let f = 0; f < frames; f++) {
    const src = (frames - 1 - f) * channels;
    for (let c = 0; c < channels; c++) out[f * channels + c] = samples[src + c];
  }
  return out;
}
function applyGain(samples, numerator, denominator) {
  const out = new Int16Array(samples.length);
  for (let i = 0; i < samples.length; i++) {
    const scaled = Math.trunc(samples[i] * numerator / denominator);
    out[i] = Math.max(-32768, Math.min(32767, scaled));
  }
  return out;
}
function silence(frames, channels) {
  return new Int16Array(Math.max(0, frames) * channels);
}
function concatSamples(parts) {
  let total = 0;
  for (const p of parts) total += p.length;
  const out = new Int16Array(total);
  let offset = 0;
  for (const p of parts) {
    out.set(p, offset);
    offset += p.length;
  }
  return out;
}

// src/domain/alchemy/research-configuration.ts
var RESEARCH_CONFIGURATION_SCHEMA_VERSION = 1;
function deriveParameters(seed, totalFrames) {
  const rng = seededRandom(seed);
  const fragmentCount = 3 + Math.floor(rng() * 6);
  const fragments = fragmentEvenly(totalFrames, fragmentCount);
  const indices = fragments.map((_, i) => i);
  const order = shuffleWithSeed(indices, rng);
  const reversedFragments = order.filter(() => rng() < 0.4);
  const silenceFrames = Math.floor(rng() * 800);
  const gainNumerator = 6 + Math.floor(rng() * 5);
  return {
    fragmentCount: fragments.length,
    reversedFragments,
    silenceFrames,
    gainNumerator,
    gainDenominator: 10,
    order
  };
}
function renderVariation(audio, seed) {
  const frames = audio.samples.length / audio.channels;
  const params = deriveParameters(seed, frames);
  const fragments = fragmentEvenly(frames, params.fragmentCount);
  const reversed = new Set(params.reversedFragments);
  const gap = silence(params.silenceFrames, audio.channels);
  const parts = [];
  params.order.forEach((fragmentIndex, position) => {
    const fragment = fragments[fragmentIndex];
    if (!fragment) return;
    let piece = sliceFragment(audio, fragment);
    if (reversed.has(fragmentIndex)) piece = reverseFrames(piece, audio.channels);
    const numerator = Math.max(3, params.gainNumerator - position);
    piece = applyGain(piece, numerator, params.gainDenominator);
    parts.push(piece);
    if (position < params.order.length - 1 && gap.length > 0) parts.push(gap);
  });
  return { ...audio, samples: concatSamples(parts) };
}
var FRAGMENT_EXPLORATION_V1 = {
  id: "fragment-exploration-v1",
  name: "Fragment exploration",
  version: "1.0.0",
  schemaVersion: RESEARCH_CONFIGURATION_SCHEMA_VERSION,
  implementationVersion: "1.0.0",
  inputConstraints: { requiredEncoding: "pcm16-wav", minFrames: 64, maxChannels: 2 },
  operations: [
    { operation: "fragment", description: "divide the input into deterministic fragments" },
    { operation: "reorder", description: "permute fragments using the variation seed" },
    { operation: "reverse", description: "reverse a seed-selected subset of fragments" },
    { operation: "space", description: "insert controlled silence between fragments" },
    { operation: "gain", description: "integer gain shaping decaying across positions" },
    { operation: "reconstruct", description: "rebuild a canonical PCM16 WAV result" }
  ],
  parameterRanges: {
    fragmentCount: { min: 3, max: 8, description: "number of deterministic fragments" },
    silenceFrames: { min: 0, max: 799, description: "frames of silence between fragments" },
    gainNumerator: { min: 3, max: 10, description: "integer gain numerator over denominator 10" }
  },
  defaultVariationCount: 8,
  seedStrategy: "base-plus-index",
  variationSeed: (baseSeed, index) => baseSeed + index * 7919 >>> 0,
  render: (inputBytes, seed) => encodeWav(renderVariation(decodeWav(inputBytes), seed))
};
function describeParameters(seed, totalFrames) {
  return deriveParameters(seed, totalFrames);
}

// src/domain/alchemy/service.ts
var SCHEMA_VERSION = 1;
var AlchemyService = class {
  #records;
  #content;
  #registry;
  #clock;
  constructor(records, content, registry, clock = () => Date.now()) {
    this.#records = records;
    this.#content = content;
    this.#registry = registry;
    this.#clock = clock;
  }
  // ---- agents --------------------------------------------------------------
  async registerAgent(input) {
    const existing = await this.#records.lookup({
      collection: COLLECTIONS.agents,
      index: "agt_by_kind_name_version",
      eq: [input.kind, input.name, input.version],
      limit: 1
    });
    if (existing.items.length > 0) return existing.items[0];
    const agent = {
      id: newUuid(),
      kind: input.kind,
      name: input.name,
      version: input.version,
      metadata: input.metadata ?? {},
      status: "active",
      schemaVersion: SCHEMA_VERSION,
      createdAt: this.#clock()
    };
    await this.#records.commit([
      { op: "put", collection: COLLECTIONS.agents, record: agent }
    ]);
    return agent;
  }
  async #requireAgent(agentId) {
    const a = await this.#records.get(COLLECTIONS.agents, agentId);
    if (!a) throw new NotFoundError(COLLECTIONS.agents, agentId);
    return a;
  }
  // ---- import --------------------------------------------------------------
  /**
   * Import creates a persistent Material Entity per occurrence. Two imports of
   * identical bytes produce two UUIDs and one shared content hash: entity
   * identity and content identity answer different questions.
   */
  async importMaterial(input) {
    await this.#requireAgent(input.agentId);
    const hash = contentHash(input.bytes);
    await this.#content.put(input.bytes);
    if (!await this.#content.has(hash)) {
      throw new IntegrityError(`content ${hash} not durable after write`);
    }
    const now = this.#clock();
    const material = {
      id: newUuid(),
      type: TYPE_AUDIO_MATERIAL,
      role: ROLE_MATERIAL,
      lifecycleState: LIFECYCLE.promoted,
      // imported deliberately by a human agent
      schemaVersion: SCHEMA_VERSION,
      createdAt: now,
      attributes: {
        contentHash: hash,
        filename: input.filename,
        byteLength: input.bytes.byteLength,
        origin: "import"
      }
    };
    this.#registry.entityType(material.type).validate?.(material.attributes);
    const transition = {
      id: newUuid(),
      subject: material.id,
      kind: TRANSITION_KIND.import,
      fromState: null,
      toState: LIFECYCLE.promoted,
      agentId: input.agentId,
      idempotencyKey: idempotencyKey("import", material.id),
      rationale: null,
      context: { contentHash: hash },
      schemaVersion: SCHEMA_VERSION,
      createdAt: now
    };
    await this.#records.commit([
      { op: "put", collection: COLLECTIONS.entities, record: material },
      { op: "put", collection: COLLECTIONS.transitions, record: transition }
    ]);
    return material;
  }
  // ---- observation ---------------------------------------------------------
  async analyzeMaterial(materialId, analyzer, analyzerAgentId) {
    const agent = await this.#requireAgent(analyzerAgentId);
    const material = await this.#requireEntity(materialId);
    const hash = String(material.attributes.contentHash);
    const bytes = await this.#content.get(hash);
    if (!bytes) throw new IntegrityError(`material ${materialId} references missing content ${hash}`);
    const metrics = analyzeBytes(analyzer, bytes);
    const observation = {
      id: newUuid(),
      subject: materialId,
      subjectKind: "entity",
      kind: KNOWLEDGE_KIND.physicalAnalysis,
      stage: "observation",
      payload: { ...metrics, sourceContentHash: hash, analysisSchemaVersion: ANALYSIS_SCHEMA_VERSION },
      agentId: agent.id,
      agentVersion: agent.version,
      evidence: [hash],
      confidence: null,
      schemaVersion: SCHEMA_VERSION,
      createdAt: this.#clock(),
      supersedes: null
    };
    await this.#records.commit([
      { op: "put", collection: COLLECTIONS.knowledge, record: observation }
    ]);
    return observation;
  }
  /** Curated human conclusion; used to demonstrate the canon view. */
  async assertKnowledge(input) {
    const agent = await this.#requireAgent(input.agentId);
    const def = this.#registry.knowledgeKind(input.kind);
    if (!def.allowedStages.includes(input.stage)) {
      throw new DomainRuleError(`stage ${input.stage} not allowed for kind ${input.kind}`);
    }
    const record = {
      id: newUuid(),
      subject: input.subject,
      subjectKind: "entity",
      kind: input.kind,
      stage: input.stage,
      payload: input.payload,
      agentId: agent.id,
      agentVersion: agent.version,
      evidence: input.evidence ?? [],
      confidence: input.confidence ?? null,
      schemaVersion: SCHEMA_VERSION,
      createdAt: this.#clock(),
      supersedes: input.supersedes ?? null
    };
    await this.#records.commit([
      { op: "put", collection: COLLECTIONS.knowledge, record }
    ]);
    return record;
  }
  // ---- research intent and experiments -------------------------------------
  async createResearchIntent(input) {
    await this.#requireAgent(input.agentId);
    const intent = {
      id: newUuid(),
      type: TYPE_RESEARCH_INTENT,
      role: "research",
      lifecycleState: "active",
      schemaVersion: SCHEMA_VERSION,
      createdAt: this.#clock(),
      attributes: {
        question: input.question,
        successCriteria: input.successCriteria ?? null
      }
    };
    await this.#records.commit([
      { op: "put", collection: COLLECTIONS.entities, record: intent }
    ]);
    return intent;
  }
  /** An Experiment without a pre-existing Research Intent is an invalid state. */
  async createExperiment(input) {
    await this.#requireAgent(input.agentId);
    if (!input.researchIntentId) {
      throw new DomainRuleError("experiment requires at least one Research Intent");
    }
    const intent = await this.#records.get(COLLECTIONS.entities, input.researchIntentId);
    if (!intent || intent.type !== TYPE_RESEARCH_INTENT) {
      throw new DomainRuleError(
        `experiment references a Research Intent that does not exist: ${input.researchIntentId}`
      );
    }
    if (input.inputMaterialIds.length === 0) {
      throw new DomainRuleError("experiment requires at least one input material");
    }
    const now = this.#clock();
    const experiment = {
      id: newUuid(),
      type: TYPE_EXPERIMENT,
      role: "research",
      lifecycleState: "recorded",
      schemaVersion: SCHEMA_VERSION,
      createdAt: now,
      attributes: {
        operation: input.operation,
        parameters: input.parameters ?? {},
        implementationVersion: input.configuration?.implementationVersion ?? IMPLEMENTATION_VERSION,
        executionAgentId: input.agentId,
        ...input.configuration ? {
          configurationId: input.configuration.id,
          configurationVersion: input.configuration.version,
          configurationSchemaVersion: input.configuration.schemaVersion,
          operationSequence: input.configuration.operations.map((o) => o.operation),
          baseSeed: input.baseSeed ?? null
        } : {}
      }
    };
    const mutations = [
      { op: "put", collection: COLLECTIONS.entities, record: experiment },
      {
        op: "put",
        collection: COLLECTIONS.relationships,
        record: this.#relationship(
          REL.investigatesIntent,
          experiment.id,
          input.researchIntentId,
          input.agentId,
          now
        )
      }
    ];
    for (const materialId of input.inputMaterialIds) {
      const m = await this.#requireEntity(materialId);
      mutations.push({
        op: "put",
        collection: COLLECTIONS.relationships,
        record: this.#relationship(
          REL.inputTo,
          m.id,
          experiment.id,
          input.agentId,
          now,
          { inputContentHash: m.attributes.contentHash }
        )
      });
    }
    await this.#records.commit(mutations);
    return experiment;
  }
  /** Runs the experiment and returns a runtime Preview. Nothing is persisted. */
  async runExperiment(experimentId) {
    const experiment = await this.#requireEntity(experimentId);
    const inputs = await this.#experimentInputs(experimentId);
    if (inputs.length === 0) throw new DomainRuleError(`experiment ${experimentId} has no inputs`);
    const source = inputs[0];
    const hash = String(source.attributes.contentHash);
    const bytes = await this.#content.get(hash);
    if (!bytes) throw new IntegrityError(`missing content ${hash} for material ${source.id}`);
    const operation = experiment.attributes.operation;
    const parameters = experiment.attributes.parameters ?? {};
    const outputBytes = applyOperation(operation, bytes, parameters);
    const outputHash = contentHash(outputBytes);
    return {
      kind: "preview",
      stagingRef: idempotencyKey("preview", experimentId, outputHash),
      experimentId,
      sourceMaterialIds: inputs.map((m) => m.id),
      operation,
      parameters,
      implementationVersion: String(experiment.attributes.implementationVersion),
      bytes: outputBytes,
      contentHash: outputHash
    };
  }
  /**
   * Execute one ResearchConfiguration over a Material and return a runtime
   * Preview Set. Nothing is persisted: each variation stays runtime state until
   * an explicit Retain, exactly as ADR-008 requires.
   */
  async runResearchConfiguration(input) {
    const agent = await this.#requireAgent(input.agentId);
    const material = await this.#requireEntity(input.materialId);
    const intent = await this.#records.get(COLLECTIONS.entities, input.researchIntentId);
    if (!intent || intent.type !== TYPE_RESEARCH_INTENT) {
      throw new DomainRuleError(
        `exploration references a Research Intent that does not exist: ${input.researchIntentId}`
      );
    }
    const hash = String(material.attributes.contentHash);
    const bytes = await this.#content.get(hash);
    if (!bytes) throw new IntegrityError(`missing content ${hash} for material ${material.id}`);
    const cfg = input.configuration;
    const audio = decodeWav(bytes);
    const frames = audio.samples.length / audio.channels;
    if (frames < cfg.inputConstraints.minFrames) {
      throw new DomainRuleError(
        `material ${material.id} has ${frames} frames, below the configuration minimum of ${cfg.inputConstraints.minFrames}`
      );
    }
    if (audio.channels > cfg.inputConstraints.maxChannels) {
      throw new DomainRuleError(
        `material ${material.id} has ${audio.channels} channels, above the configuration maximum of ${cfg.inputConstraints.maxChannels}`
      );
    }
    const experiment = await this.createExperiment({
      researchIntentId: input.researchIntentId,
      inputMaterialIds: [material.id],
      operation: "exploration",
      parameters: {},
      agentId: input.agentId,
      configuration: cfg,
      baseSeed: input.baseSeed
    });
    const count = input.variationCount ?? cfg.defaultVariationCount;
    const variations = [];
    for (let index = 0; index < count; index++) {
      const seed = cfg.variationSeed(input.baseSeed, index);
      const outputBytes = cfg.render(bytes, seed);
      const outputHash = contentHash(outputBytes);
      const preview = {
        kind: "preview",
        stagingRef: idempotencyKey("preview", experiment.id, String(seed), outputHash),
        experimentId: experiment.id,
        sourceMaterialIds: [material.id],
        operation: cfg.id,
        parameters: { configurationId: cfg.id, configurationVersion: cfg.version, seed },
        implementationVersion: cfg.implementationVersion,
        bytes: outputBytes,
        contentHash: outputHash,
        exploration: {
          configurationId: cfg.id,
          configurationVersion: cfg.version,
          variationIndex: index,
          seed
        }
      };
      variations.push({
        index,
        seed,
        preview,
        derivedParameters: describeParameters(seed, frames)
      });
    }
    return {
      kind: "preview-set",
      researchIntentId: input.researchIntentId,
      sourceMaterialIds: [material.id],
      configurationId: cfg.id,
      configurationVersion: cfg.version,
      implementationVersion: cfg.implementationVersion,
      baseSeed: input.baseSeed,
      variations,
      executionAgentId: agent.id,
      createdAt: this.#clock()
    };
  }
  /** Discard: allow runtime state to disappear. No canonical record is written. */
  discardPreview(_preview) {
  }
  // ---- retain / promote / reject ------------------------------------------
  /**
   * Retain is the explicit boundary from runtime to persistent identity.
   * Order is the guarantee: content bytes first (verified), then one bounded
   * atomic batch of semantic record mutations. No domain decision occurs inside
   * the commit, and no transaction is held open while deciding what to write.
   */
  async retain(preview, agentId, rationale) {
    await this.#requireAgent(agentId);
    const key = idempotencyKey("retain", preview.stagingRef);
    const prior = await this.#records.lookup({
      collection: COLLECTIONS.transitions,
      index: "tra_by_idempotency",
      eq: [key],
      limit: 1
    });
    if (prior.items.length > 0) {
      const t = prior.items[0];
      return { material: await this.#requireEntity(t.subject), transition: t, created: false };
    }
    await this.#content.put(preview.bytes);
    if (!await this.#content.has(preview.contentHash)) {
      throw new IntegrityError(`content ${preview.contentHash} not durable after write`);
    }
    const now = this.#clock();
    const material = {
      id: newUuid(),
      type: TYPE_AUDIO_MATERIAL,
      role: ROLE_MATERIAL,
      lifecycleState: LIFECYCLE.retained,
      schemaVersion: SCHEMA_VERSION,
      createdAt: now,
      attributes: {
        contentHash: preview.contentHash,
        byteLength: preview.bytes.byteLength,
        origin: preview.exploration ? "exploration" : "experiment",
        operation: preview.operation,
        parameters: preview.parameters,
        implementationVersion: preview.implementationVersion,
        ...preview.exploration ? {
          configurationId: preview.exploration.configurationId,
          configurationVersion: preview.exploration.configurationVersion,
          variationIndex: preview.exploration.variationIndex,
          seed: preview.exploration.seed
        } : {}
      }
    };
    this.#registry.entityType(material.type).validate?.(material.attributes);
    const intentId = await this.#intentOfExperiment(preview.experimentId);
    const transition = {
      id: newUuid(),
      subject: material.id,
      kind: TRANSITION_KIND.retain,
      fromState: null,
      toState: LIFECYCLE.retained,
      agentId,
      idempotencyKey: key,
      rationale: rationale ?? null,
      context: {
        stagingRef: preview.stagingRef,
        experimentId: preview.experimentId,
        researchIntentId: intentId,
        outputContentHash: preview.contentHash,
        implementationVersion: preview.implementationVersion
      },
      schemaVersion: SCHEMA_VERSION,
      createdAt: now
    };
    const mutations = [
      { op: "put", collection: COLLECTIONS.entities, record: material },
      { op: "put", collection: COLLECTIONS.transitions, record: transition },
      {
        op: "put",
        collection: COLLECTIONS.relationships,
        record: this.#relationship(
          REL.producedByExperiment,
          material.id,
          preview.experimentId,
          agentId,
          now
        )
      },
      {
        op: "put",
        collection: COLLECTIONS.relationships,
        record: this.#relationship(
          REL.outputOf,
          material.id,
          preview.experimentId,
          agentId,
          now
        )
      }
    ];
    for (const sourceId of preview.sourceMaterialIds) {
      mutations.push({
        op: "put",
        collection: COLLECTIONS.relationships,
        record: this.#relationship(
          REL.derivedFrom,
          material.id,
          sourceId,
          agentId,
          now,
          { operation: preview.operation }
        )
      });
    }
    await this.#records.commit(mutations);
    return { material, transition, created: true };
  }
  async promote(materialId, agentId, rationale) {
    return this.#lifecycle(materialId, LIFECYCLE.promoted, TRANSITION_KIND.promote, agentId, rationale);
  }
  async reject(materialId, agentId, rationale) {
    return this.#lifecycle(materialId, LIFECYCLE.rejected, TRANSITION_KIND.reject, agentId, rationale);
  }
  async #lifecycle(materialId, target, kind, agentId, rationale) {
    await this.#requireAgent(agentId);
    const material = await this.#requireEntity(materialId);
    const key = idempotencyKey(kind, materialId, target);
    if (material.lifecycleState === target) {
      const prior = await this.#records.lookup({
        collection: COLLECTIONS.transitions,
        index: "tra_by_idempotency",
        eq: [key],
        limit: 1
      });
      if (prior.items.length > 0) {
        return { material, transition: prior.items[0], changed: false };
      }
    }
    this.#registry.assertTransitionAllowed(material.type, material.lifecycleState, target);
    const now = this.#clock();
    const updated = { ...material, lifecycleState: target, updatedAt: now };
    const transition = {
      id: newUuid(),
      subject: materialId,
      kind,
      fromState: material.lifecycleState,
      toState: target,
      agentId,
      idempotencyKey: key,
      rationale: rationale ?? null,
      context: {},
      schemaVersion: SCHEMA_VERSION,
      createdAt: now
    };
    await this.#records.commit([
      { op: "put", collection: COLLECTIONS.entities, record: updated },
      { op: "put", collection: COLLECTIONS.transitions, record: transition }
    ]);
    return { material: updated, transition, changed: true };
  }
  // ---- helpers -------------------------------------------------------------
  #relationship(type, source, target, agentId, createdAt, metadata = {}) {
    return {
      id: newUuid(),
      type,
      source,
      target,
      agentId,
      evidence: [],
      metadata,
      schemaVersion: SCHEMA_VERSION,
      createdAt
    };
  }
  async #requireEntity(id) {
    const e = await this.#records.get(COLLECTIONS.entities, id);
    if (!e) throw new NotFoundError(COLLECTIONS.entities, id);
    return e;
  }
  async #experimentInputs(experimentId) {
    const page = await this.#records.adjacencyByTarget({
      nodeId: experimentId,
      type: REL.inputTo,
      limit: 100
    });
    const ids = page.items.map((r) => r.source);
    const rows = await this.#records.getMany(COLLECTIONS.entities, ids);
    return rows.filter((r) => r !== null);
  }
  async #intentOfExperiment(experimentId) {
    const page = await this.#records.adjacencyBySource({
      nodeId: experimentId,
      type: REL.investigatesIntent,
      limit: 1
    });
    return page.items.length > 0 ? page.items[0].target : null;
  }
};

// src/query/traversal.ts
async function traverse(store, startId, options) {
  const pageSize = options.pageSize ?? 100;
  const maxDepth = options.maxDepth ?? Number.POSITIVE_INFINITY;
  const maxNodes = options.maxNodes ?? 1e4;
  const visited = /* @__PURE__ */ new Set([startId]);
  const nodes = [];
  const edges = [];
  const cyclesDetected = [];
  let truncated = false;
  let frontier = [startId];
  let depth = 0;
  while (frontier.length > 0 && depth < maxDepth) {
    const next = [];
    for (const nodeId of frontier) {
      let after;
      for (; ; ) {
        const page = options.direction === "ancestors" ? await store.adjacencyBySource({
          nodeId,
          type: options.relationshipType,
          after,
          limit: pageSize
        }) : await store.adjacencyByTarget({
          nodeId,
          type: options.relationshipType,
          after,
          limit: pageSize
        });
        for (const raw of page.items) {
          const rel = raw;
          edges.push(rel);
          const neighbour = options.direction === "ancestors" ? rel.target : rel.source;
          if (visited.has(neighbour)) {
            cyclesDetected.push(`${rel.source}->${rel.target}`);
            continue;
          }
          visited.add(neighbour);
          if (visited.size > maxNodes) {
            truncated = true;
            break;
          }
          next.push(neighbour);
        }
        if (truncated || page.nextAfter === null) break;
        after = page.nextAfter;
      }
      if (truncated) break;
    }
    depth += 1;
    for (const id of next) nodes.push({ id, depth });
    if (truncated) break;
    frontier = next;
  }
  nodes.sort((a, b) => a.depth - b.depth || (a.id < b.id ? -1 : a.id > b.id ? 1 : 0));
  return { nodes, edges, cyclesDetected, truncated };
}

// src/query/queries.ts
var AlchemyQueries = class {
  #records;
  #content;
  constructor(records, content) {
    this.#records = records;
    this.#content = content;
  }
  /** Q1. Default Inventory: role = material AND lifecycleState = promoted. */
  async promotedMaterials(after, limit = 50) {
    const page = await this.#records.lookup({
      collection: COLLECTIONS.entities,
      index: "ent_by_role_lifecycle",
      prefix: [ROLE_MATERIAL, LIFECYCLE.promoted],
      after,
      limit
    });
    return { items: page.items, nextAfter: page.nextAfter };
  }
  /** Q7. Retained and rejected materials, deliberately outside the Inventory. */
  async materialsByLifecycle(state, after, limit = 50) {
    const page = await this.#records.lookup({
      collection: COLLECTIONS.entities,
      index: "ent_by_role_lifecycle",
      prefix: [ROLE_MATERIAL, state],
      after,
      limit
    });
    return { items: page.items, nextAfter: page.nextAfter };
  }
  /** Q2. Observations for one material, grouped by Agent and Agent version. */
  async observationsForMaterial(materialId) {
    const out = /* @__PURE__ */ new Map();
    let after;
    for (; ; ) {
      const page = await this.#records.lookup({
        collection: COLLECTIONS.knowledge,
        index: "kno_by_subject_kind_agent",
        prefix: [materialId, KNOWLEDGE_KIND.physicalAnalysis],
        after,
        limit: 100
      });
      for (const raw of page.items) {
        const k = raw;
        const groupKey = `${k.agentId}@${k.agentVersion}`;
        const bucket = out.get(groupKey) ?? [];
        bucket.push(k);
        out.set(groupKey, bucket);
      }
      if (page.nextAfter === null) break;
      after = page.nextAfter;
    }
    return out;
  }
  /** Q3. */
  ancestors(materialId, maxDepth) {
    return traverse(this.#records, materialId, {
      relationshipType: REL.derivedFrom,
      direction: "ancestors",
      maxDepth
    });
  }
  /** Q4. */
  descendants(materialId, maxDepth) {
    return traverse(this.#records, materialId, {
      relationshipType: REL.derivedFrom,
      direction: "descendants",
      maxDepth
    });
  }
  /** Q5. */
  async experimentsForIntent(intentId) {
    const page = await this.#records.adjacencyByTarget({
      nodeId: intentId,
      type: REL.investigatesIntent,
      limit: 200
    });
    const ids = page.items.map((r) => r.source);
    const rows = await this.#records.getMany(COLLECTIONS.entities, ids);
    return rows.filter((r) => r !== null);
  }
  /** Q6. */
  async experimentInputsOutputs(experimentId) {
    const incoming = await this.#records.adjacencyByTarget({
      nodeId: experimentId,
      limit: 200
    });
    const inputIds = [];
    const outputIds = [];
    for (const raw of incoming.items) {
      const rel = raw;
      if (rel.type === REL.inputTo) inputIds.push(rel.source);
      if (rel.type === REL.outputOf) outputIds.push(rel.source);
    }
    const [inputs, outputs] = await Promise.all([
      this.#records.getMany(COLLECTIONS.entities, inputIds),
      this.#records.getMany(COLLECTIONS.entities, outputIds)
    ]);
    return {
      inputs: inputs.filter((r) => r !== null),
      outputs: outputs.filter((r) => r !== null)
    };
  }
  /** Q8. Compare two analyzer versions without mutating either result. */
  async compareAnalyzerVersions(materialId, versionA, versionB) {
    const grouped = await this.observationsForMaterial(materialId);
    const pick = (version) => {
      for (const [key, list] of grouped) {
        if (key.endsWith(`@${version}`) && list.length > 0) {
          return [...list].sort((x, y) => y.createdAt - x.createdAt)[0];
        }
      }
      return null;
    };
    const a = pick(versionA);
    const b = pick(versionB);
    const metrics = /* @__PURE__ */ new Set([
      ...Object.keys(a?.payload ?? {}),
      ...Object.keys(b?.payload ?? {})
    ]);
    return [...metrics].sort().map((metric) => {
      const av = typeof a?.payload[metric] === "number" ? a.payload[metric] : null;
      const bv = typeof b?.payload[metric] === "number" ? b.payload[metric] : null;
      return { metric, a: av, b: bv, equal: av === bv };
    });
  }
  /** Q9. Canon is a view over Knowledge, never a separate store. */
  async canonKnowledgeForSubject(subjectId, limit = 100) {
    const page = await this.#records.lookup({
      collection: COLLECTIONS.knowledge,
      index: "kno_by_subject_stage",
      prefix: [subjectId, "canon"],
      limit
    });
    return page.items;
  }
  /**
   * Q10. Integrity audit. Deliberately a paginated full-corpus operation: no
   * index can answer "which references are broken", and pretending otherwise
   * would be dishonest. Never on an interactive path.
   */
  async integrityAudit() {
    const entityIds = /* @__PURE__ */ new Set();
    const referencedHashes = /* @__PURE__ */ new Set();
    const materialsWithMissingContent = [];
    for await (const rec of this.#scanAll(COLLECTIONS.entities)) {
      const e = rec;
      entityIds.add(e.id);
      const hash = e.attributes?.contentHash;
      if (typeof hash === "string") {
        referencedHashes.add(hash);
        if (!await this.#content.has(hash)) materialsWithMissingContent.push(e.id);
      }
    }
    const danglingRelationships = [];
    for await (const rec of this.#scanAll(COLLECTIONS.relationships)) {
      const r = rec;
      if (!entityIds.has(r.source) || !entityIds.has(r.target)) danglingRelationships.push(r.id);
    }
    const orphanKnowledge = [];
    for await (const rec of this.#scanAll(COLLECTIONS.knowledge)) {
      const k = rec;
      if (k.subjectKind === "entity" && !entityIds.has(k.subject)) orphanKnowledge.push(k.id);
    }
    const unreferencedContentBlobs = (await this.#content.list()).filter((h) => !referencedHashes.has(h));
    return {
      danglingRelationships,
      orphanKnowledge,
      materialsWithMissingContent,
      unreferencedContentBlobs
    };
  }
  /** Q11. Distinct entities sharing content, reported and never merged. */
  async duplicateContentGroups() {
    const groups = /* @__PURE__ */ new Map();
    let after;
    for (; ; ) {
      const page = await this.#records.lookup({
        collection: COLLECTIONS.entities,
        index: "ent_by_content_hash",
        range: {},
        after,
        limit: 200
      });
      for (const raw of page.items) {
        const e = raw;
        const hash = e.attributes?.contentHash;
        if (typeof hash !== "string") continue;
        const bucket = groups.get(hash) ?? [];
        bucket.push(e.id);
        groups.set(hash, bucket);
      }
      if (page.nextAfter === null) break;
      after = page.nextAfter;
    }
    for (const [hash, ids] of groups) if (ids.length < 2) groups.delete(hash);
    return groups;
  }
  async transitionsFor(subjectId) {
    const page = await this.#records.lookup({
      collection: COLLECTIONS.transitions,
      index: "tra_by_subject",
      prefix: [subjectId],
      limit: 100
    });
    return page.items;
  }
  async *#scanAll(collection) {
    let after = null;
    for (; ; ) {
      const page = await this.#records.scan(collection, after, 200);
      for (const item of page.items) yield item;
      if (page.nextAfter === null) break;
      after = String(page.nextAfter[0]);
    }
  }
};

// src/migrations/index.ts
var CURRENT_SCHEMA = SCHEMA_V1;

// src/adapters/web-audio/normalize.ts
var PREFERRED_MIME_TYPES = [
  "audio/wav",
  // PCM
  "audio/mp4; codecs=alac",
  // ALAC, lossless
  "audio/mp4;codecs=alac",
  "audio/webm; codecs=opus",
  "audio/webm",
  "audio/mp4"
  // AAC fallback
];
function detectRecorderCapability(recorder = globalThis.MediaRecorder) {
  if (!recorder || typeof recorder.isTypeSupported !== "function") {
    return { mimeType: null, lossless: false };
  }
  for (const type of PREFERRED_MIME_TYPES) {
    if (recorder.isTypeSupported(type)) {
      return { mimeType: type, lossless: /wav|alac/i.test(type) };
    }
  }
  return { mimeType: null, lossless: false };
}
async function normalizeToCanonicalWav(input, createContext, options = {}) {
  const sampleRate = options.sampleRate ?? 44100;
  const targetChannels = Math.max(1, options.channels ?? 1);
  const ctx = createContext(sampleRate);
  const decoded = await ctx.decodeAudioData(input.slice(0));
  ctx.close?.();
  const maxFrames = options.maxSeconds ? Math.min(decoded.length, Math.floor(options.maxSeconds * decoded.sampleRate)) : decoded.length;
  const sourceChannels = decoded.numberOfChannels;
  const channelData = [];
  for (let c = 0; c < sourceChannels; c++) channelData.push(decoded.getChannelData(c));
  const samples = new Int16Array(maxFrames * targetChannels);
  for (let f = 0; f < maxFrames; f++) {
    for (let c = 0; c < targetChannels; c++) {
      let value;
      if (targetChannels === 1 && sourceChannels > 1) {
        let sum = 0;
        for (let s = 0; s < sourceChannels; s++) sum += channelData[s][f] ?? 0;
        value = sum / sourceChannels;
      } else {
        value = channelData[Math.min(c, sourceChannels - 1)][f] ?? 0;
      }
      const clamped = Math.max(-1, Math.min(1, value));
      samples[f * targetChannels + c] = Math.max(-32768, Math.min(32767, Math.round(clamped * 32767)));
    }
  }
  const canonical = {
    sampleRate: decoded.sampleRate,
    channels: targetChannels,
    samples
  };
  return encodeWav(canonical);
}

// src/web/lab.ts
var DEFAULT_INTENT = "Exploraci\xF3n libre";
async function openWebLab() {
  const records = await IndexedDbRecordStore.open("alchemy-records", CURRENT_SCHEMA);
  if (await records.schemaVersion() < CURRENT_SCHEMA.version) {
    await records.setSchemaVersion(CURRENT_SCHEMA.version);
  }
  const content = await IndexedDbContentStore.open("alchemy-content");
  const registry = new DataRegistry();
  registerAlchemyVocabulary(registry);
  const service = new AlchemyService(records, content, registry);
  const queries = new AlchemyQueries(records, content);
  const artist = await service.registerAgent({ kind: "human", name: "artist", version: "1" });
  const analyzer = await service.registerAgent({
    kind: "analyzer",
    name: "physical-analyzer",
    version: "1.0.0"
  });
  const intentCache = /* @__PURE__ */ new Map();
  async function intentFor(question) {
    const key = question || DEFAULT_INTENT;
    const cached = intentCache.get(key);
    if (cached) return cached;
    const intent = await service.createResearchIntent({ question: key, agentId: artist.id });
    intentCache.set(key, intent.id);
    return intent.id;
  }
  const audioContext = (rate) => {
    const Ctor = window;
    const Impl = Ctor.AudioContext ?? Ctor.webkitAudioContext;
    return new Impl({ sampleRate: rate });
  };
  return {
    recorderCapability: detectRecorderCapability(),
    async ingest(input, filename) {
      const bytes = await normalizeToCanonicalWav(
        input,
        audioContext,
        { channels: 1, maxSeconds: 120 }
      );
      const material = await service.importMaterial({
        bytes,
        filename: filename.replace(/\.[^.]+$/, "") + ".wav",
        agentId: artist.id
      });
      await service.analyzeMaterial(material.id, ANALYZER_V1, analyzer.id);
      return material;
    },
    async explore(materialId, question, variations) {
      return service.runResearchConfiguration({
        materialId,
        configuration: FRAGMENT_EXPLORATION_V1,
        researchIntentId: await intentFor(question),
        baseSeed: Date.now() >>> 0,
        variationCount: variations,
        agentId: artist.id
      });
    },
    async retain(preview) {
      return (await service.retain(preview, artist.id)).material;
    },
    async promote(materialId) {
      await service.promote(materialId, artist.id);
    },
    async reject(materialId) {
      await service.reject(materialId, artist.id);
    },
    async materials(state) {
      const page = state === LIFECYCLE.promoted ? await queries.promotedMaterials(void 0, 100) : await queries.materialsByLifecycle(state, void 0, 100);
      return [...page.items].reverse();
    },
    async material(id) {
      for (const state of [LIFECYCLE.promoted, LIFECYCLE.retained]) {
        const page = await queries.materialsByLifecycle(state, void 0, 200);
        const found = page.items.find((m) => m.id === id);
        if (found) return found;
      }
      return null;
    },
    async audioFor(material) {
      return content.get(String(material.attributes.contentHash));
    }
  };
}
export {
  openWebLab
};
export { openWebLab as openLab };
